<a href="https://colab.research.google.com/github/christo444/Dark-Guard/blob/main/Dark_guard_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import sklearn
import pandas as pd
import numpy as np

print("Python:", sys.version)
print("scikit-learn:", sklearn.__version__)
print("pandas:", pd.__version__)
print("numpy:", np.__version__)

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
scikit-learn: 1.6.1
pandas: 2.2.3
numpy: 2.1.3

In [2]:
DATA_URL = "https://raw.githubusercontent.com/yamanalab/ec-darkpattern/master/dataset/dataset.tsv"
df = pd.read_csv(DATA_URL, sep="\t")

print("Shape:", df.shape)                       # expect (2356, 4)
print("Columns:", list(df.columns))              # page_id, text, label, Pattern Category
print("Missing values:\n", df.isnull().sum())    # expect all zero
print("Duplicate rows:", df.duplicated().sum())  # expect 0
print("Label counts:\n", df["label"].value_counts())  # expect 1178 / 1178

Shape: (2356, 4)
Columns: ['page_id', 'text', 'label', 'Pattern Category']
Missing values:
 page_id             0
text                0
label               0
Pattern Category    0
dtype: int64
Duplicate rows: 0
Label counts:
 label
1    1178
0    1178
Name: count, dtype: int64

In [3]:
from sklearn.model_selection import StratifiedGroupKFold

outer = StratifiedGroupKFold(n_splits=7, shuffle=True, random_state=42)
trainval_idx, test_idx = next(
    outer.split(df["text"], df["label"], groups=df["page_id"])
)
trainval_df = df.iloc[trainval_idx].reset_index(drop=True)
test_df = df.iloc[test_idx].reset_index(drop=True)

overlap = set(trainval_df.page_id) & set(test_df.page_id)
print(f"Train+val pool: {len(trainval_df)} rows")
print(f"Held-out test:  {len(test_df)} rows")
print(f"page_id overlap (must be 0): {len(overlap)}")
# expect: 2019 / 337 / 0

Train+val pool: 2072 rows
Held-out test:  284 rows
page_id overlap (must be 0): 0

In [4]:
inner = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
cv_splits = list(
    inner.split(trainval_df["text"], trainval_df["label"], groups=trainval_df["page_id"])
)

for fold, (tr_idx, val_idx) in enumerate(cv_splits, start=1):
    tr, val = trainval_df.iloc[tr_idx], trainval_df.iloc[val_idx]
    fold_overlap = set(tr.page_id) & set(val.page_id)
    print(f"Fold {fold}: train={len(tr)} val={len(val)} "
          f"val_labels={val['label'].value_counts().to_dict()} "
          f"page_id_overlap={len(fold_overlap)}")

Fold 1: train=1693 val=379 val_labels={1: 200, 0: 179} page_id_overlap=0
Fold 2: train=1691 val=381 val_labels={1: 206, 0: 175} page_id_overlap=0
Fold 3: train=1674 val=398 val_labels={1: 203, 0: 195} page_id_overlap=0
Fold 4: train=1511 val=561 val_labels={0: 366, 1: 195} page_id_overlap=0
Fold 5: train=1719 val=353 val_labels={1: 207, 0: 146} page_id_overlap=0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

rf_rows = []
for fold, (tr_idx, val_idx) in enumerate(cv_splits, start=1):
    tr, val = trainval_df.iloc[tr_idx], trainval_df.iloc[val_idx]

    vectorizer = CountVectorizer()
    X_tr = vectorizer.fit_transform(tr["text"])
    X_val = vectorizer.transform(val["text"])

    clf = RandomForestClassifier(
        n_estimators=641, max_depth=32, min_samples_split=18,
        min_samples_leaf=1, bootstrap=False, random_state=42, n_jobs=-1
    )
    clf.fit(X_tr, tr["label"])
    preds = clf.predict(X_val)

    acc = accuracy_score(val["label"], preds)
    prec = precision_score(val["label"], preds)
    rec = recall_score(val["label"], preds)
    f1 = f1_score(val["label"], preds)
    rf_rows.append([fold, acc, prec, rec, f1])
    print(f"Fold {fold}: acc={acc:.4f} prec={prec:.4f} rec={rec:.4f} f1={f1:.4f}")

rf_arr = np.array([r[1:] for r in rf_rows])
print()
print(f"RF Mean:  acc={rf_arr[:,0].mean():.4f} prec={rf_arr[:,1].mean():.4f} "
      f"rec={rf_arr[:,2].mean():.4f} f1={rf_arr[:,3].mean():.4f}")
print(f"RF Std:   acc={rf_arr[:,0].std():.4f} prec={rf_arr[:,1].std():.4f} "
      f"rec={rf_arr[:,2].std():.4f} f1={rf_arr[:,3].std():.4f}")

Fold 1: acc=0.9578 prec=0.9842 rec=0.9350 f1=0.9590
Fold 2: acc=0.9370 prec=0.9840 rec=0.8981 f1=0.9391
Fold 3: acc=0.9422 prec=0.9500 rec=0.9360 f1=0.9429
Fold 4: acc=0.9554 prec=0.9293 rec=0.9436 f1=0.9364
Fold 5: acc=0.9235 prec=0.9639 rec=0.9034 f1=0.9327

RF Mean:  acc=0.9432 prec=0.9623 rec=0.9232 f1=0.9420
RF Std:   acc=0.0126 prec=0.0210 rec=0.0187 f1=0.0091

In [6]:
from sklearn.svm import SVC

svm_rows = []
for fold, (tr_idx, val_idx) in enumerate(cv_splits, start=1):
    tr, val = trainval_df.iloc[tr_idx], trainval_df.iloc[val_idx]

    vectorizer = CountVectorizer()
    X_tr = vectorizer.fit_transform(tr["text"])
    X_val = vectorizer.transform(val["text"])

    clf = SVC(kernel="rbf", C=4.35, random_state=42)
    clf.fit(X_tr, tr["label"])
    preds = clf.predict(X_val)

    acc = accuracy_score(val["label"], preds)
    prec = precision_score(val["label"], preds)
    rec = recall_score(val["label"], preds)
    f1 = f1_score(val["label"], preds)
    svm_rows.append([fold, acc, prec, rec, f1])
    print(f"Fold {fold}: acc={acc:.4f} prec={prec:.4f} rec={rec:.4f} f1={f1:.4f}")

svm_arr = np.array([r[1:] for r in svm_rows])
print()
print(f"SVM Mean: acc={svm_arr[:,0].mean():.4f} prec={svm_arr[:,1].mean():.4f} "
      f"rec={svm_arr[:,2].mean():.4f} f1={svm_arr[:,3].mean():.4f}")
print(f"SVM Std:  acc={svm_arr[:,0].std():.4f} prec={svm_arr[:,1].std():.4f} "
      f"rec={svm_arr[:,2].std():.4f} f1={svm_arr[:,3].std():.4f}")

Fold 1: acc=0.9551 prec=0.9692 rec=0.9450 f1=0.9570
Fold 2: acc=0.9370 prec=0.9643 rec=0.9175 f1=0.9403
Fold 3: acc=0.9271 prec=0.9223 rec=0.9360 f1=0.9291
Fold 4: acc=0.9537 prec=0.9333 rec=0.9333 f1=0.9333
Fold 5: acc=0.9405 prec=0.9895 rec=0.9082 f1=0.9471

SVM Mean: acc=0.9427 prec=0.9557 rec=0.9280 f1=0.9414
SVM Std:  acc=0.0105 prec=0.0245 rec=0.0133 f1=0.0099

In [7]:
summary = pd.DataFrame({
    "Model": ["Random Forest", "SVM"],
    "Accuracy": [rf_arr[:,0].mean(), svm_arr[:,0].mean()],
    "Precision": [rf_arr[:,1].mean(), svm_arr[:,1].mean()],
    "Recall": [rf_arr[:,2].mean(), svm_arr[:,2].mean()],
    "F1": [rf_arr[:,3].mean(), svm_arr[:,3].mean()],
    "Std (Accuracy)": [rf_arr[:,0].std(), svm_arr[:,0].std()],
})
print(summary.to_string(index=False))

        Model  Accuracy  Precision   Recall       F1  Std (Accuracy)
Random Forest  0.943190   0.962293 0.923198 0.942009        0.012564
          SVM  0.942691   0.955731 0.927996 0.941358        0.010529

In [8]:
import pandas as pd
df = pd.read_csv("darkguard_split_v1.tsv", sep="\t")
print(df["split"].value_counts())

split
trainval    2072
test         284
Name: count, dtype: int64

In [9]:
!pip install -q transformers

from transformers import AutoTokenizer
tok = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "FLASH SALE | LIMITED TIME ONLY Shop Now"
print("Original text:", repr(text))
print()

# Step 1: split into raw tokens (no numbers yet)
tokens = tok.tokenize(text)
print("Step 1 - Tokens:", tokens)
print()

# Step 2: convert to numeric IDs + add BERT's special tokens ([CLS], [SEP])
encoded = tok(text, padding="max_length", max_length=16, truncation=True)
print("Step 2 - input_ids:", encoded["input_ids"])
print("Step 3 - attention_mask:", encoded["attention_mask"])
print()

# Step 4: show id <-> token side by side
for tid, mask in zip(encoded["input_ids"], encoded["attention_mask"]):
    piece = tok.convert_ids_to_tokens([tid])[0]
    print(f"  id={tid:>6}  token={piece!r:<15}  attention_mask={mask}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Original text: 'FLASH SALE | LIMITED TIME ONLY Shop Now'

Step 1 - Tokens: ['flash', 'sale', '|', 'limited', 'time', 'only', 'shop', 'now']

Step 2 - input_ids: [101, 5956, 5096, 1064, 3132, 2051, 2069, 4497, 2085, 102, 0, 0, 0, 0, 0, 0]
Step 3 - attention_mask: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]

  id=   101  token='[CLS]'          attention_mask=1
  id=  5956  token='flash'          attention_mask=1
  id=  5096  token='sale'           attention_mask=1
  id=  1064  token='|'              attention_mask=1
  id=  3132  token='limited'        attention_mask=1
  id=  2051  token='time'           attention_mask=1
  id=  2069  token='only'           attention_mask=1
  id=  4497  token='shop'           attention_mask=1
  id=  2085  token='now'            attention_mask=1
  id=   102  token='[SEP]'          attention_mask=1
  id=     0  token='[PAD]'          attention_mask=0
  id=     0  token='[PAD]'          attention_mask=0
  id=     0  token='[PAD]'          attention_mask=0
  id=     0  token='[PAD]'          attention_mask=0
  id=     0  token='[PAD]'          attention_mask=0
  id=     0  token='[PAD]'          attention_mask=0

In [10]:
from transformers import AutoTokenizer
tok = AutoTokenizer.from_pretrained("bert-base-uncased")

text = ("CANCELLATION POLICY: If you are not completely satisfied with Yogi Surprise, "
        "you can cancel your membership and discontinue your monthly payments at any time. "
        "In order to cancel before you are renewed for the next shipment, you need to contact "
        "Yogi Surprise prior to the renewal date on the 14th of each month. Email: "
        "support@yogisurprise.com and we\u2019ll respond promptly. If your membership has already "
        "renewed and you\u2019d like to cancel an upcoming shipment, you must request cancellation "
        "by the 3rd of the month to be eligible for a refund. IF YOU DO NOT CANCEL PRIOR TO THE "
        "THIRD DAY OF A CALENDAR MONTH, YOU CANNOT BE REFUNDED FOR THAT MONTH\u2019S SHIPMENT. "
        "WE DO NOT OFFER REFUNDS ON BOXES THAT HAVE ALREADY BEEN SHIPPED. To request cancellation, "
        "simply click here and submit the contact form or email us: support@yogisurprise.com. "
        "We\u2019ll get back to promptly!")

# 1. How many tokens does this text actually need, with NO truncation?
full_tokens = tok.tokenize(text)
print("Total tokens needed (no truncation):", len(full_tokens))
print()

# 2. Show where the brand name / email address get split
interesting = [t for t in full_tokens if "yogi" in t.lower() or "surprise" in t.lower() or "yogisurprise" in t.lower() or "@" in t or "##" in t]
print("Tokens touching the brand name / email (watch for ## pieces):")
print(interesting[:25])
print()

# 3. Compare what survives at three different max_length settings
for max_len in [32, 64, 128]:
    encoded = tok(text, padding="max_length", max_length=max_len, truncation=True)
    kept = sum(encoded["attention_mask"])
    decoded_kept = tok.decode(encoded["input_ids"], skip_special_tokens=True)
    print(f"--- max_length={max_len} ---")
    print(f"Real tokens kept: {kept - 2} of {len(full_tokens)}")  # -2 for CLS/SEP
    print(f"What survives: {decoded_kept[:200]}...")
    print()

Total tokens needed (no truncation): 192

Tokens touching the brand name / email (watch for ## pieces):
['##gi', 'surprise', '##nti', '##nu', '##e', '##gi', 'surprise', '@', '##gis', '##ur', '##pr', '##ise', '##und', '##und', '##ed', '##unds', '@', '##gis', '##ur', '##pr', '##ise']

--- max_length=32 ---
Real tokens kept: 30 of 192
What survives: cancellation policy : if you are not completely satisfied with yogi surprise, you can cancel your membership and discontinue your monthly payments at any time...

--- max_length=64 ---
Real tokens kept: 62 of 192
What survives: cancellation policy : if you are not completely satisfied with yogi surprise, you can cancel your membership and discontinue your monthly payments at any time. in order to cancel before you are renewe...

--- max_length=128 ---
Real tokens kept: 126 of 192
What survives: cancellation policy : if you are not completely satisfied with yogi surprise, you can cancel your membership and discontinue your monthly payments at any time. in order to cancel before you are renewe...

In [11]:
from transformers import AutoTokenizer
import pandas as pd

tok = AutoTokenizer.from_pretrained("bert-base-uncased")
df = pd.read_csv("darkguard_split_v1.tsv", sep="\t")
trainval = df[df["split"] == "trainval"]

lengths = trainval["text"].apply(lambda t: len(tok.tokenize(str(t))))

print("Token length distribution across the training pool:")
print(lengths.describe())
print()
for p in [50, 75, 90, 95, 99, 100]:
    print(f"  {p}th percentile: {lengths.quantile(p/100):.0f} tokens")

Token length distribution across the training pool:
count    2072.000000
mean        9.847490
std        14.766193
min         0.000000
25%         4.000000
50%         6.000000
75%        10.000000
max       192.000000
Name: text, dtype: float64

  50th percentile: 6 tokens
  75th percentile: 10 tokens
  90th percentile: 19 tokens
  95th percentile: 27 tokens
  99th percentile: 82 tokens
  100th percentile: 192 tokens

In [12]:
from transformers import AutoTokenizer
import pandas as pd

tok = AutoTokenizer.from_pretrained("bert-base-uncased")
df = pd.read_csv("darkguard_split_v1.tsv", sep="\t")
trainval = df[df["split"] == "trainval"]

lengths = trainval["text"].apply(lambda t: len(tok.tokenize(str(t))))

print("Token length distribution across the training pool:")
print(lengths.describe())
print()
for p in [50, 75, 90, 95, 99, 100]:
    print(f"  {p}th percentile: {lengths.quantile(p/100):.0f} tokens")

Token length distribution across the training pool:
count    2072.000000
mean        9.847490
std        14.766193
min         0.000000
25%         4.000000
50%         6.000000
75%        10.000000
max       192.000000
Name: text, dtype: float64

  50th percentile: 6 tokens
  75th percentile: 10 tokens
  90th percentile: 19 tokens
  95th percentile: 27 tokens
  99th percentile: 82 tokens
  100th percentile: 192 tokens

In [13]:
# Part A: find the empty/near-empty rows
empty_rows = trainval[trainval["text"].apply(lambda t: len(tok.tokenize(str(t))) == 0)]
print("Rows with 0 tokens:")
print(empty_rows[["page_id", "text", "label", "Pattern Category"]])
print()

# Part B: exact truncation counts at candidate max_length values
for max_len in [16, 32, 64, 128]:
    # -2 reserves room for [CLS] and [SEP]
    truncated = (lengths > (max_len - 2)).sum()
    pct = truncated / len(lengths) * 100
    print(f"max_length={max_len}: {truncated} of {len(lengths)} rows truncated ({pct:.1f}%)")

Rows with 0 tokens:
      page_id text  label  Pattern Category
1099      568          0  Not Dark Pattern

max_length=16: 307 of 2072 rows truncated (14.8%)
max_length=32: 88 of 2072 rows truncated (4.2%)
max_length=64: 27 of 2072 rows truncated (1.3%)
max_length=128: 9 of 2072 rows truncated (0.4%)

In [14]:
import pandas as pd
from transformers import AutoTokenizer

MAX_LENGTH = 64

tok = AutoTokenizer.from_pretrained("bert-base-uncased")
df = pd.read_csv("darkguard_split_v1.tsv", sep="\t")

# Section 4 cleaning decision: drop the one icon-font artifact row we found
def has_pua(text):
    return any(0xE000 <= ord(c) <= 0xF8FF for c in str(text))

before = len(df)
df = df[~df["text"].apply(has_pua)].reset_index(drop=True)
print(f"Dropped {before - len(df)} row(s). New shape: {df.shape}")

# Encode every remaining row in one call
encodings = tok(
    list(df["text"]),
    padding="max_length",
    truncation=True,
    max_length=MAX_LENGTH,
)

print("Number of encoded rows:", len(encodings["input_ids"]))
print("Length of input_ids for row 0:", len(encodings["input_ids"][0]))
print("Length of attention_mask for row 0:", len(encodings["attention_mask"][0]))
print()
print("Row 0 text:", df.iloc[0]["text"])
print("Row 0 label:", df.iloc[0]["label"])
print("Row 0 input_ids:", encodings["input_ids"][0])

Dropped 1 row(s). New shape: (2355, 6)
Number of encoded rows: 2355
Length of input_ids for row 0: 64
Length of attention_mask for row 0: 64

Row 0 text: FLASH SALE | LIMITED TIME ONLY Shop Now
Row 0 label: 1
Row 0 input_ids: [101, 5956, 5096, 1064, 3132, 2051, 2069, 4497, 2085, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [15]:
import torch

# 1. GPU check
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

# 2. Wrap encodings + labels into a Dataset
class DarkPatternDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

full_dataset = DarkPatternDataset(encodings, list(df["label"]))

# sanity check on one item
sample = full_dataset[0]
print()
print("Sample keys:", sample.keys())
print("input_ids shape:", sample["input_ids"].shape)
print("attention_mask shape:", sample["attention_mask"].shape)
print("label:", sample["labels"].item())

CUDA available: True
GPU name: Tesla T4

Sample keys: dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])
input_ids shape: torch.Size([64])
attention_mask shape: torch.Size([64])
label: 1

In [16]:
import numpy as np
from torch.utils.data import Subset
from transformers import BertForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

FOLD = 1

train_idx = df.index[(df["split"] == "trainval") & (df["cv_fold"] != FOLD)].tolist()
val_idx   = df.index[(df["split"] == "trainval") & (df["cv_fold"] == FOLD)].tolist()

train_dataset = Subset(full_dataset, train_idx)
val_dataset   = Subset(full_dataset, val_idx)

print(f"Fold {FOLD}: train={len(train_dataset)}  val={len(val_dataset)}")

model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "precision": precision_score(labels, preds),
        "recall": recall_score(labels, preds),
        "f1": f1_score(labels, preds),
    }

training_args = TrainingArguments(
    output_dir="./bert_fold1_output",
    num_train_epochs=4,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    seed=42,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=20,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

trainer.train()
final_metrics = trainer.evaluate()
print(final_metrics)

Fold 1: train=1693  val=378

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': 0.11889512091875076, 'eval_accuracy': 0.9656084656084656, 'eval_precision': 0.9516908212560387, 'eval_recall': 0.985, 'eval_f1': 0.9680589680589681}

In [17]:
import numpy as np

all_fold_metrics = []

for FOLD in range(1, 6):
    train_idx = df.index[(df["split"] == "trainval") & (df["cv_fold"] != FOLD)].tolist()
    val_idx   = df.index[(df["split"] == "trainval") & (df["cv_fold"] == FOLD)].tolist()

    train_dataset = Subset(full_dataset, train_idx)
    val_dataset   = Subset(full_dataset, val_idx)

    model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

    training_args = TrainingArguments(
        output_dir=f"./bert_fold{FOLD}_output",
        num_train_epochs=4,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        seed=42,
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=50,
        report_to="none",
        disable_tqdm=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    metrics = trainer.evaluate()
    metrics["fold"] = FOLD
    all_fold_metrics.append(metrics)
    print(f"Fold {FOLD} done: acc={metrics['eval_accuracy']:.4f} f1={metrics['eval_f1']:.4f}")

acc = [m["eval_accuracy"] for m in all_fold_metrics]
prec = [m["eval_precision"] for m in all_fold_metrics]
rec = [m["eval_recall"] for m in all_fold_metrics]
f1 = [m["eval_f1"] for m in all_fold_metrics]

print()
print(f"Mean accuracy:  {np.mean(acc):.4f}  (std {np.std(acc):.4f})")
print(f"Mean precision: {np.mean(prec):.4f}  (std {np.std(prec):.4f})")
print(f"Mean recall:    {np.mean(rec):.4f}  (std {np.std(rec):.4f})")
print(f"Mean f1:        {np.mean(f1):.4f}  (std {np.std(f1):.4f})")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3558', 'grad_norm': '6.399', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.1406', 'grad_norm': '25.53', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.1573', 'eval_accuracy': '0.9471', 'eval_precision': '0.9327', 'eval_recall': '0.97', 'eval_f1': '0.951', 'eval_runtime': '1.433', 'eval_samples_per_second': '263.8', 'eval_steps_per_second': '16.75', 'epoch': '1'}
{'loss': '0.09641', 'grad_norm': '2.014', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.09305', 'grad_norm': '4.941', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.106', 'eval_accuracy': '0.9683', 'eval_precision': '0.9747', 'eval_recall': '0.965', 'eval_f1': '0.9698', 'eval_runtime': '1.498', 'eval_samples_per_second': '252.3', 'eval_steps_per_second': '16.02', 'epoch': '2'}
{'loss': '0.04437', 'grad_norm': '0.0993', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.0324', 'grad_norm': '6.699', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1838', 'eval_accuracy': '0.955', 'eval_precision': '0.942', 'eval_recall': '0.975', 'eval_f1': '0.9582', 'eval_runtime': '1.447', 'eval_samples_per_second': '261.2', 'eval_steps_per_second': '16.59', 'epoch': '3'}
{'loss': '0.03625', 'grad_norm': '0.0419', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.02783', 'grad_norm': '0.03574', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.1756', 'eval_accuracy': '0.955', 'eval_precision': '0.942', 'eval_recall': '0.975', 'eval_f1': '0.9582', 'eval_runtime': '1.433', 'eval_samples_per_second': '263.9', 'eval_steps_per_second': '16.75', 'epoch': '4'}
{'train_runtime': '85.86', 'train_samples_per_second': '78.88', 'train_steps_per_second': '4.938', 'train_loss': '0.0976', 'epoch': '4'}
{'eval_loss': '0.1756', 'eval_accuracy': '0.955', 'eval_precision': '0.942', 'eval_recall': '0.975', 'eval_f1': '0.9582', 'eval_runtime': '1.423', 'eval_samples_per_second': '265.7', 'eval_steps_per_second': '16.87', 'epoch': '4'}
Fold 1 done: acc=0.9550 f1=0.9582

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3994', 'grad_norm': '4.112', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.1414', 'grad_norm': '18.31', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.2063', 'eval_accuracy': '0.9318', 'eval_precision': '0.9787', 'eval_recall': '0.8932', 'eval_f1': '0.934', 'eval_runtime': '1.47', 'eval_samples_per_second': '259.2', 'eval_steps_per_second': '16.33', 'epoch': '1'}
{'loss': '0.09769', 'grad_norm': '0.4892', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.08057', 'grad_norm': '4.293', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1782', 'eval_accuracy': '0.9423', 'eval_precision': '0.9299', 'eval_recall': '0.966', 'eval_f1': '0.9476', 'eval_runtime': '1.463', 'eval_samples_per_second': '260.4', 'eval_steps_per_second': '16.4', 'epoch': '2'}
{'loss': '0.05255', 'grad_norm': '0.06163', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.03121', 'grad_norm': '3.056', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1679', 'eval_accuracy': '0.958', 'eval_precision': '0.9524', 'eval_recall': '0.9709', 'eval_f1': '0.9615', 'eval_runtime': '1.458', 'eval_samples_per_second': '261.3', 'eval_steps_per_second': '16.46', 'epoch': '3'}
{'loss': '0.01897', 'grad_norm': '0.0812', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.02447', 'grad_norm': '0.02641', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.1751', 'eval_accuracy': '0.9528', 'eval_precision': '0.9563', 'eval_recall': '0.9563', 'eval_f1': '0.9563', 'eval_runtime': '1.473', 'eval_samples_per_second': '258.7', 'eval_steps_per_second': '16.3', 'epoch': '4'}
{'train_runtime': '83.96', 'train_samples_per_second': '80.51', 'train_steps_per_second': '5.05', 'train_loss': '0.101', 'epoch': '4'}
{'eval_loss': '0.1751', 'eval_accuracy': '0.9528', 'eval_precision': '0.9563', 'eval_recall': '0.9563', 'eval_f1': '0.9563', 'eval_runtime': '1.446', 'eval_samples_per_second': '263.5', 'eval_steps_per_second': '16.6', 'epoch': '4'}
Fold 2 done: acc=0.9528 f1=0.9563

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4052', 'grad_norm': '11.29', 'learning_rate': '1.767e-05', 'epoch': '0.4762'}
{'loss': '0.1573', 'grad_norm': '3.323', 'learning_rate': '1.529e-05', 'epoch': '0.9524'}
{'eval_loss': '0.115', 'eval_accuracy': '0.9648', 'eval_precision': '0.9896', 'eval_recall': '0.9409', 'eval_f1': '0.9646', 'eval_runtime': '1.524', 'eval_samples_per_second': '261.1', 'eval_steps_per_second': '16.4', 'epoch': '1'}
{'loss': '0.08335', 'grad_norm': '3.87', 'learning_rate': '1.29e-05', 'epoch': '1.429'}
{'loss': '0.0731', 'grad_norm': '0.1258', 'learning_rate': '1.052e-05', 'epoch': '1.905'}
{'eval_loss': '0.1778', 'eval_accuracy': '0.9548', 'eval_precision': '1', 'eval_recall': '0.9113', 'eval_f1': '0.9536', 'eval_runtime': '1.524', 'eval_samples_per_second': '261.1', 'eval_steps_per_second': '16.4', 'epoch': '2'}
{'loss': '0.04121', 'grad_norm': '0.07494', 'learning_rate': '8.143e-06', 'epoch': '2.381'}
{'loss': '0.03964', 'grad_norm': '0.1126', 'learning_rate': '5.762e-06', 'epoch': '2.857'}
{'eval_loss': '0.1454', 'eval_accuracy': '0.9623', 'eval_precision': '0.9747', 'eval_recall': '0.9507', 'eval_f1': '0.9626', 'eval_runtime': '1.531', 'eval_samples_per_second': '259.9', 'eval_steps_per_second': '16.33', 'epoch': '3'}
{'loss': '0.01334', 'grad_norm': '0.03382', 'learning_rate': '3.381e-06', 'epoch': '3.333'}
{'loss': '0.01089', 'grad_norm': '16.48', 'learning_rate': '1e-06', 'epoch': '3.81'}
{'eval_loss': '0.1665', 'eval_accuracy': '0.9598', 'eval_precision': '0.9606', 'eval_recall': '0.9606', 'eval_f1': '0.9606', 'eval_runtime': '1.525', 'eval_samples_per_second': '261', 'eval_steps_per_second': '16.39', 'epoch': '4'}
{'train_runtime': '83.25', 'train_samples_per_second': '80.39', 'train_steps_per_second': '5.045', 'train_loss': '0.09912', 'epoch': '4'}
{'eval_loss': '0.1665', 'eval_accuracy': '0.9598', 'eval_precision': '0.9606', 'eval_recall': '0.9606', 'eval_f1': '0.9606', 'eval_runtime': '1.515', 'eval_samples_per_second': '262.6', 'eval_steps_per_second': '16.5', 'epoch': '4'}
Fold 3 done: acc=0.9598 f1=0.9606

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4068', 'grad_norm': '10.62', 'learning_rate': '1.742e-05', 'epoch': '0.5263'}
{'eval_loss': '0.1315', 'eval_accuracy': '0.9626', 'eval_precision': '0.9394', 'eval_recall': '0.9538', 'eval_f1': '0.9466', 'eval_runtime': '2.196', 'eval_samples_per_second': '255.4', 'eval_steps_per_second': '16.39', 'epoch': '1'}
{'loss': '0.1474', 'grad_norm': '1.082', 'learning_rate': '1.479e-05', 'epoch': '1.053'}
{'loss': '0.08339', 'grad_norm': '2.725', 'learning_rate': '1.216e-05', 'epoch': '1.579'}
{'eval_loss': '0.1113', 'eval_accuracy': '0.9715', 'eval_precision': '0.9686', 'eval_recall': '0.9487', 'eval_f1': '0.9585', 'eval_runtime': '2.15', 'eval_samples_per_second': '260.9', 'eval_steps_per_second': '16.75', 'epoch': '2'}
{'loss': '0.06663', 'grad_norm': '0.124', 'learning_rate': '9.526e-06', 'epoch': '2.105'}
{'loss': '0.01582', 'grad_norm': '0.1892', 'learning_rate': '6.895e-06', 'epoch': '2.632'}
{'eval_loss': '0.1215', 'eval_accuracy': '0.9715', 'eval_precision': '0.9686', 'eval_recall': '0.9487', 'eval_f1': '0.9585', 'eval_runtime': '2.15', 'eval_samples_per_second': '260.9', 'eval_steps_per_second': '16.75', 'epoch': '3'}
{'loss': '0.07607', 'grad_norm': '0.2048', 'learning_rate': '4.263e-06', 'epoch': '3.158'}
{'loss': '0.005928', 'grad_norm': '0.04182', 'learning_rate': '1.632e-06', 'epoch': '3.684'}
{'eval_loss': '0.1274', 'eval_accuracy': '0.9715', 'eval_precision': '0.9686', 'eval_recall': '0.9487', 'eval_f1': '0.9585', 'eval_runtime': '2.155', 'eval_samples_per_second': '260.4', 'eval_steps_per_second': '16.71', 'epoch': '4'}
{'train_runtime': '78.65', 'train_samples_per_second': '76.8', 'train_steps_per_second': '4.832', 'train_loss': '0.1082', 'epoch': '4'}
{'eval_loss': '0.1274', 'eval_accuracy': '0.9715', 'eval_precision': '0.9686', 'eval_recall': '0.9487', 'eval_f1': '0.9585', 'eval_runtime': '2.136', 'eval_samples_per_second': '262.6', 'eval_steps_per_second': '16.86', 'epoch': '4'}
Fold 4 done: acc=0.9715 f1=0.9585

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3695', 'grad_norm': '9.517', 'learning_rate': '1.773e-05', 'epoch': '0.463'}
{'loss': '0.157', 'grad_norm': '19.35', 'learning_rate': '1.542e-05', 'epoch': '0.9259'}
{'eval_loss': '0.1492', 'eval_accuracy': '0.9462', 'eval_precision': '0.9393', 'eval_recall': '0.971', 'eval_f1': '0.9549', 'eval_runtime': '1.363', 'eval_samples_per_second': '259', 'eval_steps_per_second': '16.88', 'epoch': '1'}
{'loss': '0.1197', 'grad_norm': '1.26', 'learning_rate': '1.31e-05', 'epoch': '1.389'}
{'loss': '0.04601', 'grad_norm': '1.561', 'learning_rate': '1.079e-05', 'epoch': '1.852'}
{'eval_loss': '0.1388', 'eval_accuracy': '0.9717', 'eval_precision': '0.9805', 'eval_recall': '0.971', 'eval_f1': '0.9757', 'eval_runtime': '1.359', 'eval_samples_per_second': '259.7', 'eval_steps_per_second': '16.92', 'epoch': '2'}
{'loss': '0.04234', 'grad_norm': '0.1091', 'learning_rate': '8.472e-06', 'epoch': '2.315'}
{'loss': '0.0317', 'grad_norm': '0.08713', 'learning_rate': '6.157e-06', 'epoch': '2.778'}
{'eval_loss': '0.1367', 'eval_accuracy': '0.9717', 'eval_precision': '0.9852', 'eval_recall': '0.9662', 'eval_f1': '0.9756', 'eval_runtime': '1.371', 'eval_samples_per_second': '257.5', 'eval_steps_per_second': '16.77', 'epoch': '3'}
{'loss': '0.0353', 'grad_norm': '0.04967', 'learning_rate': '3.843e-06', 'epoch': '3.241'}
{'loss': '0.01145', 'grad_norm': '0.03932', 'learning_rate': '1.528e-06', 'epoch': '3.704'}
{'eval_loss': '0.1459', 'eval_accuracy': '0.9717', 'eval_precision': '0.9852', 'eval_recall': '0.9662', 'eval_f1': '0.9756', 'eval_runtime': '1.359', 'eval_samples_per_second': '259.7', 'eval_steps_per_second': '16.92', 'epoch': '4'}
{'train_runtime': '85.37', 'train_samples_per_second': '80.5', 'train_steps_per_second': '5.061', 'train_loss': '0.09775', 'epoch': '4'}
{'eval_loss': '0.1459', 'eval_accuracy': '0.9717', 'eval_precision': '0.9852', 'eval_recall': '0.9662', 'eval_f1': '0.9756', 'eval_runtime': '1.348', 'eval_samples_per_second': '261.9', 'eval_steps_per_second': '17.07', 'epoch': '4'}
Fold 5 done: acc=0.9717 f1=0.9756

Mean accuracy:  0.9621  (std 0.0080)
Mean precision: 0.9625  (std 0.0142)
Mean recall:    0.9614  (std 0.0089)
Mean f1:        0.9619  (std 0.0070)

In [18]:
import time
from transformers import AutoTokenizer, DistilBertForSequenceClassification

# Re-tokenize with DistilBERT's own tokenizer (verify, don't assume, it matches BERT's)
distil_tok = AutoTokenizer.from_pretrained("distilbert-base-uncased")

distil_encodings = distil_tok(
    list(df["text"]),
    padding="max_length",
    truncation=True,
    max_length=MAX_LENGTH,
)

# Quick check: does it tokenize identically to BERT's tokenizer on row 0?
print("BERT input_ids[0]:      ", encodings["input_ids"][0])
print("DistilBERT input_ids[0]:", distil_encodings["input_ids"][0])
print("Identical:", encodings["input_ids"][0] == distil_encodings["input_ids"][0])
print()

distil_dataset = DarkPatternDataset(distil_encodings, list(df["label"]))

distil_fold_metrics = []

for FOLD in range(1, 6):
    train_idx = df.index[(df["split"] == "trainval") & (df["cv_fold"] != FOLD)].tolist()
    val_idx   = df.index[(df["split"] == "trainval") & (df["cv_fold"] == FOLD)].tolist()

    train_dataset = Subset(distil_dataset, train_idx)
    val_dataset   = Subset(distil_dataset, val_idx)

    model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

    training_args = TrainingArguments(
        output_dir=f"./distilbert_fold{FOLD}_output",
        num_train_epochs=4,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        seed=42,
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=50,
        report_to="none",
        disable_tqdm=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
    )

    start = time.time()
    trainer.train()
    elapsed = time.time() - start

    metrics = trainer.evaluate()
    metrics["fold"] = FOLD
    metrics["train_time_sec"] = elapsed
    distil_fold_metrics.append(metrics)
    print(f"Fold {FOLD} done: acc={metrics['eval_accuracy']:.4f} f1={metrics['eval_f1']:.4f} time={elapsed:.1f}s")

acc = [m["eval_accuracy"] for m in distil_fold_metrics]
f1 = [m["eval_f1"] for m in distil_fold_metrics]
times = [m["train_time_sec"] for m in distil_fold_metrics]

print()
print(f"DistilBERT Mean accuracy: {np.mean(acc):.4f} (std {np.std(acc):.4f})")
print(f"DistilBERT Mean f1:       {np.mean(f1):.4f} (std {np.std(f1):.4f})")
print(f"DistilBERT Mean train time per fold: {np.mean(times):.1f}s")

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

BERT input_ids[0]:       [101, 5956, 5096, 1064, 3132, 2051, 2069, 4497, 2085, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
DistilBERT input_ids[0]: [101, 5956, 5096, 1064, 3132, 2051, 2069, 4497, 2085, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Identical: True

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3789', 'grad_norm': '3.989', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.1641', 'grad_norm': '3.203', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.1556', 'eval_accuracy': '0.9339', 'eval_precision': '0.9679', 'eval_recall': '0.905', 'eval_f1': '0.9354', 'eval_runtime': '0.7306', 'eval_samples_per_second': '517.4', 'eval_steps_per_second': '32.85', 'epoch': '1'}
{'loss': '0.1035', 'grad_norm': '3.619', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.08816', 'grad_norm': '5.066', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1278', 'eval_accuracy': '0.9603', 'eval_precision': '0.9793', 'eval_recall': '0.945', 'eval_f1': '0.9618', 'eval_runtime': '0.7324', 'eval_samples_per_second': '516.1', 'eval_steps_per_second': '32.77', 'epoch': '2'}
{'loss': '0.06165', 'grad_norm': '0.1311', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.05363', 'grad_norm': '13.03', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1811', 'eval_accuracy': '0.9471', 'eval_precision': '0.9369', 'eval_recall': '0.965', 'eval_f1': '0.9507', 'eval_runtime': '0.7351', 'eval_samples_per_second': '514.2', 'eval_steps_per_second': '32.65', 'epoch': '3'}
{'loss': '0.04216', 'grad_norm': '0.08029', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.03504', 'grad_norm': '0.0512', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.175', 'eval_accuracy': '0.9577', 'eval_precision': '0.9554', 'eval_recall': '0.965', 'eval_f1': '0.9602', 'eval_runtime': '0.733', 'eval_samples_per_second': '515.7', 'eval_steps_per_second': '32.74', 'epoch': '4'}
{'train_runtime': '42.81', 'train_samples_per_second': '158.2', 'train_steps_per_second': '9.904', 'train_loss': '0.1107', 'epoch': '4'}
{'eval_loss': '0.175', 'eval_accuracy': '0.9577', 'eval_precision': '0.9554', 'eval_recall': '0.965', 'eval_f1': '0.9602', 'eval_runtime': '0.7242', 'eval_samples_per_second': '522', 'eval_steps_per_second': '33.14', 'epoch': '4'}
Fold 1 done: acc=0.9577 f1=0.9602 time=43.3s

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3834', 'grad_norm': '0.9774', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.1435', 'grad_norm': '8.311', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.1691', 'eval_accuracy': '0.9449', 'eval_precision': '0.9947', 'eval_recall': '0.9029', 'eval_f1': '0.9466', 'eval_runtime': '0.7349', 'eval_samples_per_second': '518.4', 'eval_steps_per_second': '32.66', 'epoch': '1'}
{'loss': '0.09847', 'grad_norm': '0.3786', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.07317', 'grad_norm': '1.766', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1448', 'eval_accuracy': '0.9606', 'eval_precision': '0.9659', 'eval_recall': '0.9612', 'eval_f1': '0.9635', 'eval_runtime': '0.7311', 'eval_samples_per_second': '521.1', 'eval_steps_per_second': '32.83', 'epoch': '2'}
{'loss': '0.06493', 'grad_norm': '0.09445', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.0452', 'grad_norm': '2.606', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1337', 'eval_accuracy': '0.958', 'eval_precision': '0.9657', 'eval_recall': '0.9563', 'eval_f1': '0.961', 'eval_runtime': '0.7419', 'eval_samples_per_second': '513.5', 'eval_steps_per_second': '32.35', 'epoch': '3'}
{'loss': '0.03465', 'grad_norm': '0.06946', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.02753', 'grad_norm': '0.04462', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.1581', 'eval_accuracy': '0.9554', 'eval_precision': '0.9565', 'eval_recall': '0.9612', 'eval_f1': '0.9588', 'eval_runtime': '0.7424', 'eval_samples_per_second': '513.2', 'eval_steps_per_second': '32.33', 'epoch': '4'}
{'train_runtime': '42.66', 'train_samples_per_second': '158.5', 'train_steps_per_second': '9.939', 'train_loss': '0.1051', 'epoch': '4'}
{'eval_loss': '0.1581', 'eval_accuracy': '0.9554', 'eval_precision': '0.9565', 'eval_recall': '0.9612', 'eval_f1': '0.9588', 'eval_runtime': '0.7375', 'eval_samples_per_second': '516.6', 'eval_steps_per_second': '32.54', 'epoch': '4'}
Fold 2 done: acc=0.9554 f1=0.9588 time=43.0s

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3996', 'grad_norm': '4.914', 'learning_rate': '1.767e-05', 'epoch': '0.4762'}
{'loss': '0.1436', 'grad_norm': '5.127', 'learning_rate': '1.529e-05', 'epoch': '0.9524'}
{'eval_loss': '0.1394', 'eval_accuracy': '0.9623', 'eval_precision': '0.9563', 'eval_recall': '0.9704', 'eval_f1': '0.9633', 'eval_runtime': '0.7686', 'eval_samples_per_second': '517.9', 'eval_steps_per_second': '32.53', 'epoch': '1'}
{'loss': '0.09489', 'grad_norm': '7.896', 'learning_rate': '1.29e-05', 'epoch': '1.429'}
{'loss': '0.08661', 'grad_norm': '0.3819', 'learning_rate': '1.052e-05', 'epoch': '1.905'}
{'eval_loss': '0.1182', 'eval_accuracy': '0.9724', 'eval_precision': '0.9898', 'eval_recall': '0.9557', 'eval_f1': '0.9724', 'eval_runtime': '0.7662', 'eval_samples_per_second': '519.4', 'eval_steps_per_second': '32.63', 'epoch': '2'}
{'loss': '0.02861', 'grad_norm': '0.07287', 'learning_rate': '8.143e-06', 'epoch': '2.381'}
{'loss': '0.05158', 'grad_norm': '0.1262', 'learning_rate': '5.762e-06', 'epoch': '2.857'}
{'eval_loss': '0.1275', 'eval_accuracy': '0.9698', 'eval_precision': '0.9799', 'eval_recall': '0.9606', 'eval_f1': '0.9701', 'eval_runtime': '0.7622', 'eval_samples_per_second': '522.2', 'eval_steps_per_second': '32.8', 'epoch': '3'}
{'loss': '0.02535', 'grad_norm': '0.05402', 'learning_rate': '3.381e-06', 'epoch': '3.333'}
{'loss': '0.03199', 'grad_norm': '8.182', 'learning_rate': '1e-06', 'epoch': '3.81'}
{'eval_loss': '0.1323', 'eval_accuracy': '0.9698', 'eval_precision': '0.9799', 'eval_recall': '0.9606', 'eval_f1': '0.9701', 'eval_runtime': '0.7685', 'eval_samples_per_second': '517.9', 'eval_steps_per_second': '32.53', 'epoch': '4'}
{'train_runtime': '42.24', 'train_samples_per_second': '158.4', 'train_steps_per_second': '9.943', 'train_loss': '0.1042', 'epoch': '4'}
{'eval_loss': '0.1323', 'eval_accuracy': '0.9698', 'eval_precision': '0.9799', 'eval_recall': '0.9606', 'eval_f1': '0.9701', 'eval_runtime': '0.7552', 'eval_samples_per_second': '527', 'eval_steps_per_second': '33.1', 'epoch': '4'}
Fold 3 done: acc=0.9698 f1=0.9701 time=42.6s

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3634', 'grad_norm': '3.642', 'learning_rate': '1.742e-05', 'epoch': '0.5263'}
{'eval_loss': '0.1292', 'eval_accuracy': '0.9554', 'eval_precision': '0.9208', 'eval_recall': '0.9538', 'eval_f1': '0.937', 'eval_runtime': '1.085', 'eval_samples_per_second': '517.2', 'eval_steps_per_second': '33.19', 'epoch': '1'}
{'loss': '0.1541', 'grad_norm': '0.4368', 'learning_rate': '1.479e-05', 'epoch': '1.053'}
{'loss': '0.08826', 'grad_norm': '1.963', 'learning_rate': '1.216e-05', 'epoch': '1.579'}
{'eval_loss': '0.1149', 'eval_accuracy': '0.9697', 'eval_precision': '0.9635', 'eval_recall': '0.9487', 'eval_f1': '0.9561', 'eval_runtime': '1.092', 'eval_samples_per_second': '513.9', 'eval_steps_per_second': '32.98', 'epoch': '2'}
{'loss': '0.07847', 'grad_norm': '0.8006', 'learning_rate': '9.526e-06', 'epoch': '2.105'}
{'loss': '0.02966', 'grad_norm': '22.43', 'learning_rate': '6.895e-06', 'epoch': '2.632'}
{'eval_loss': '0.1261', 'eval_accuracy': '0.9697', 'eval_precision': '0.9785', 'eval_recall': '0.9333', 'eval_f1': '0.9554', 'eval_runtime': '1.095', 'eval_samples_per_second': '512.2', 'eval_steps_per_second': '32.87', 'epoch': '3'}
{'loss': '0.0668', 'grad_norm': '0.2038', 'learning_rate': '4.263e-06', 'epoch': '3.158'}
{'loss': '0.01569', 'grad_norm': '0.04496', 'learning_rate': '1.632e-06', 'epoch': '3.684'}
{'eval_loss': '0.1274', 'eval_accuracy': '0.9697', 'eval_precision': '0.9684', 'eval_recall': '0.9436', 'eval_f1': '0.9558', 'eval_runtime': '1.078', 'eval_samples_per_second': '520.4', 'eval_steps_per_second': '33.4', 'epoch': '4'}
{'train_runtime': '39.82', 'train_samples_per_second': '151.7', 'train_steps_per_second': '9.544', 'train_loss': '0.1071', 'epoch': '4'}
{'eval_loss': '0.1274', 'eval_accuracy': '0.9697', 'eval_precision': '0.9684', 'eval_recall': '0.9436', 'eval_f1': '0.9558', 'eval_runtime': '1.072', 'eval_samples_per_second': '523.3', 'eval_steps_per_second': '33.58', 'epoch': '4'}
Fold 4 done: acc=0.9697 f1=0.9558 time=40.1s

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3731', 'grad_norm': '9.073', 'learning_rate': '1.773e-05', 'epoch': '0.463'}
{'loss': '0.1527', 'grad_norm': '3.391', 'learning_rate': '1.542e-05', 'epoch': '0.9259'}
{'eval_loss': '0.1494', 'eval_accuracy': '0.9462', 'eval_precision': '0.9434', 'eval_recall': '0.9662', 'eval_f1': '0.9547', 'eval_runtime': '0.6834', 'eval_samples_per_second': '516.5', 'eval_steps_per_second': '33.66', 'epoch': '1'}
{'loss': '0.1407', 'grad_norm': '0.4374', 'learning_rate': '1.31e-05', 'epoch': '1.389'}
{'loss': '0.06282', 'grad_norm': '1.277', 'learning_rate': '1.079e-05', 'epoch': '1.852'}
{'eval_loss': '0.1471', 'eval_accuracy': '0.9575', 'eval_precision': '0.9571', 'eval_recall': '0.971', 'eval_f1': '0.964', 'eval_runtime': '0.6847', 'eval_samples_per_second': '515.6', 'eval_steps_per_second': '33.59', 'epoch': '2'}
{'loss': '0.06028', 'grad_norm': '0.1001', 'learning_rate': '8.472e-06', 'epoch': '2.315'}
{'loss': '0.05326', 'grad_norm': '0.1394', 'learning_rate': '6.157e-06', 'epoch': '2.778'}
{'eval_loss': '0.1458', 'eval_accuracy': '0.9547', 'eval_precision': '0.9614', 'eval_recall': '0.9614', 'eval_f1': '0.9614', 'eval_runtime': '0.6793', 'eval_samples_per_second': '519.7', 'eval_steps_per_second': '33.86', 'epoch': '3'}
{'loss': '0.04404', 'grad_norm': '6.136', 'learning_rate': '3.843e-06', 'epoch': '3.241'}
{'loss': '0.02117', 'grad_norm': '0.1628', 'learning_rate': '1.528e-06', 'epoch': '3.704'}
{'eval_loss': '0.1451', 'eval_accuracy': '0.9575', 'eval_precision': '0.966', 'eval_recall': '0.9614', 'eval_f1': '0.9637', 'eval_runtime': '0.6848', 'eval_samples_per_second': '515.5', 'eval_steps_per_second': '33.59', 'epoch': '4'}
{'train_runtime': '43.15', 'train_samples_per_second': '159.3', 'train_steps_per_second': '10.01', 'train_loss': '0.1085', 'epoch': '4'}
{'eval_loss': '0.1451', 'eval_accuracy': '0.9575', 'eval_precision': '0.966', 'eval_recall': '0.9614', 'eval_f1': '0.9637', 'eval_runtime': '0.6808', 'eval_samples_per_second': '518.5', 'eval_steps_per_second': '33.78', 'epoch': '4'}
Fold 5 done: acc=0.9575 f1=0.9637 time=43.5s

DistilBERT Mean accuracy: 0.9620 (std 0.0064)
DistilBERT Mean f1:       0.9617 (std 0.0049)
DistilBERT Mean train time per fold: 42.5s

In [19]:
from transformers import AutoTokenizer, RobertaForSequenceClassification

roberta_tok = AutoTokenizer.from_pretrained("roberta-base")

roberta_encodings = roberta_tok(
    list(df["text"]),
    padding="max_length",
    truncation=True,
    max_length=MAX_LENGTH,
)

# Sanity check: RoBERTa uses a DIFFERENT tokenizer/vocabulary than BERT
# (byte-level BPE, not WordPiece) - so we expect these to differ, unlike
# the BERT/DistilBERT comparison which matched exactly.
print("BERT input_ids[0]:    ", encodings["input_ids"][0])
print("RoBERTa input_ids[0]: ", roberta_encodings["input_ids"][0])
print("Identical:", encodings["input_ids"][0] == roberta_encodings["input_ids"][0])
print()

roberta_dataset = DarkPatternDataset(roberta_encodings, list(df["label"]))

roberta_fold_metrics = []

for FOLD in range(1, 6):
    train_idx = df.index[(df["split"] == "trainval") & (df["cv_fold"] != FOLD)].tolist()
    val_idx   = df.index[(df["split"] == "trainval") & (df["cv_fold"] == FOLD)].tolist()

    train_dataset = Subset(roberta_dataset, train_idx)
    val_dataset   = Subset(roberta_dataset, val_idx)

    model = RobertaForSequenceClassification.from_pretrained("roberta-base", num_labels=2)

    training_args = TrainingArguments(
        output_dir=f"./roberta_fold{FOLD}_output",
        num_train_epochs=4,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        seed=42,
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=50,
        report_to="none",
        disable_tqdm=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
    )

    start = time.time()
    trainer.train()
    elapsed = time.time() - start

    metrics = trainer.evaluate()
    metrics["fold"] = FOLD
    metrics["train_time_sec"] = elapsed
    roberta_fold_metrics.append(metrics)
    print(f"Fold {FOLD} done: acc={metrics['eval_accuracy']:.4f} f1={metrics['eval_f1']:.4f} time={elapsed:.1f}s")

acc = [m["eval_accuracy"] for m in roberta_fold_metrics]
f1 = [m["eval_f1"] for m in roberta_fold_metrics]
times = [m["train_time_sec"] for m in roberta_fold_metrics]

print()
print(f"RoBERTa-base Mean accuracy: {np.mean(acc):.4f} (std {np.std(acc):.4f})")
print(f"RoBERTa-base Mean f1:       {np.mean(f1):.4f} (std {np.std(f1):.4f})")
print(f"RoBERTa-base Mean train time per fold: {np.mean(times):.1f}s")

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

BERT input_ids[0]:     [101, 5956, 5096, 1064, 3132, 2051, 2069, 4497, 2085, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
RoBERTa input_ids[0]:  [0, 7613, 13246, 208, 13812, 1721, 43999, 18034, 35669, 9129, 978, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Identical: False

model.safetensors: reconstructing file:   0%|          |  0.00B /  499MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4185', 'grad_norm': '13.54', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.1552', 'grad_norm': '20.66', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.1557', 'eval_accuracy': '0.9418', 'eval_precision': '0.9684', 'eval_recall': '0.92', 'eval_f1': '0.9436', 'eval_runtime': '1.351', 'eval_samples_per_second': '279.8', 'eval_steps_per_second': '17.76', 'epoch': '1'}
{'loss': '0.1068', 'grad_norm': '4.328', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.03885', 'grad_norm': '1.439', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1342', 'eval_accuracy': '0.9709', 'eval_precision': '0.9655', 'eval_recall': '0.98', 'eval_f1': '0.9727', 'eval_runtime': '1.335', 'eval_samples_per_second': '283.2', 'eval_steps_per_second': '17.98', 'epoch': '2'}
{'loss': '0.04513', 'grad_norm': '0.06937', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.01779', 'grad_norm': '0.1534', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1984', 'eval_accuracy': '0.963', 'eval_precision': '0.9429', 'eval_recall': '0.99', 'eval_f1': '0.9659', 'eval_runtime': '1.35', 'eval_samples_per_second': '280.1', 'eval_steps_per_second': '17.78', 'epoch': '3'}
{'loss': '0.02326', 'grad_norm': '0.01153', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.02212', 'grad_norm': '0.01628', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.198', 'eval_accuracy': '0.9656', 'eval_precision': '0.9474', 'eval_recall': '0.99', 'eval_f1': '0.9682', 'eval_runtime': '1.326', 'eval_samples_per_second': '285.1', 'eval_steps_per_second': '18.1', 'epoch': '4'}
{'train_runtime': '85.1', 'train_samples_per_second': '79.57', 'train_steps_per_second': '4.982', 'train_loss': '0.09826', 'epoch': '4'}
{'eval_loss': '0.198', 'eval_accuracy': '0.9656', 'eval_precision': '0.9474', 'eval_recall': '0.99', 'eval_f1': '0.9682', 'eval_runtime': '1.323', 'eval_samples_per_second': '285.6', 'eval_steps_per_second': '18.14', 'epoch': '4'}
Fold 1 done: acc=0.9656 f1=0.9682 time=85.4s

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4011', 'grad_norm': '5.025', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.1177', 'grad_norm': '12.3', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.1755', 'eval_accuracy': '0.9554', 'eval_precision': '0.9797', 'eval_recall': '0.9369', 'eval_f1': '0.9578', 'eval_runtime': '1.344', 'eval_samples_per_second': '283.4', 'eval_steps_per_second': '17.85', 'epoch': '1'}
{'loss': '0.1013', 'grad_norm': '0.2129', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.08027', 'grad_norm': '12.86', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1454', 'eval_accuracy': '0.9606', 'eval_precision': '0.9848', 'eval_recall': '0.9417', 'eval_f1': '0.9628', 'eval_runtime': '1.349', 'eval_samples_per_second': '282.3', 'eval_steps_per_second': '17.79', 'epoch': '2'}
{'loss': '0.09265', 'grad_norm': '0.2771', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.02014', 'grad_norm': '0.9146', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1548', 'eval_accuracy': '0.9711', 'eval_precision': '0.9621', 'eval_recall': '0.9854', 'eval_f1': '0.9736', 'eval_runtime': '1.358', 'eval_samples_per_second': '280.5', 'eval_steps_per_second': '17.67', 'epoch': '3'}
{'loss': '0.007917', 'grad_norm': '0.05001', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.0162', 'grad_norm': '0.01573', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.1598', 'eval_accuracy': '0.9633', 'eval_precision': '0.9706', 'eval_recall': '0.9612', 'eval_f1': '0.9659', 'eval_runtime': '1.344', 'eval_samples_per_second': '283.5', 'eval_steps_per_second': '17.86', 'epoch': '4'}
{'train_runtime': '84.97', 'train_samples_per_second': '79.56', 'train_steps_per_second': '4.99', 'train_loss': '0.1011', 'epoch': '4'}
{'eval_loss': '0.1598', 'eval_accuracy': '0.9633', 'eval_precision': '0.9706', 'eval_recall': '0.9612', 'eval_f1': '0.9659', 'eval_runtime': '1.334', 'eval_samples_per_second': '285.6', 'eval_steps_per_second': '17.99', 'epoch': '4'}
Fold 2 done: acc=0.9633 f1=0.9659 time=85.3s

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4784', 'grad_norm': '12.14', 'learning_rate': '1.767e-05', 'epoch': '0.4762'}
{'loss': '0.142', 'grad_norm': '5.145', 'learning_rate': '1.529e-05', 'epoch': '0.9524'}
{'eval_loss': '0.1266', 'eval_accuracy': '0.9648', 'eval_precision': '0.961', 'eval_recall': '0.9704', 'eval_f1': '0.9657', 'eval_runtime': '1.4', 'eval_samples_per_second': '284.2', 'eval_steps_per_second': '17.85', 'epoch': '1'}
{'loss': '0.09808', 'grad_norm': '33.67', 'learning_rate': '1.29e-05', 'epoch': '1.429'}
{'loss': '0.1298', 'grad_norm': '43.94', 'learning_rate': '1.052e-05', 'epoch': '1.905'}
{'eval_loss': '0.1341', 'eval_accuracy': '0.9698', 'eval_precision': '0.9897', 'eval_recall': '0.9507', 'eval_f1': '0.9698', 'eval_runtime': '1.398', 'eval_samples_per_second': '284.8', 'eval_steps_per_second': '17.89', 'epoch': '2'}
{'loss': '0.03345', 'grad_norm': '0.08845', 'learning_rate': '8.143e-06', 'epoch': '2.381'}
{'loss': '0.08452', 'grad_norm': '0.1999', 'learning_rate': '5.762e-06', 'epoch': '2.857'}
{'eval_loss': '0.128', 'eval_accuracy': '0.9698', 'eval_precision': '0.9751', 'eval_recall': '0.9655', 'eval_f1': '0.9703', 'eval_runtime': '1.412', 'eval_samples_per_second': '281.8', 'eval_steps_per_second': '17.7', 'epoch': '3'}
{'loss': '0.03225', 'grad_norm': '0.3445', 'learning_rate': '3.381e-06', 'epoch': '3.333'}
{'loss': '0.006801', 'grad_norm': '47.89', 'learning_rate': '1e-06', 'epoch': '3.81'}
{'eval_loss': '0.1562', 'eval_accuracy': '0.9673', 'eval_precision': '0.9703', 'eval_recall': '0.9655', 'eval_f1': '0.9679', 'eval_runtime': '1.405', 'eval_samples_per_second': '283.3', 'eval_steps_per_second': '17.79', 'epoch': '4'}
{'train_runtime': '84.08', 'train_samples_per_second': '79.59', 'train_steps_per_second': '4.995', 'train_loss': '0.1221', 'epoch': '4'}
{'eval_loss': '0.1562', 'eval_accuracy': '0.9673', 'eval_precision': '0.9703', 'eval_recall': '0.9655', 'eval_f1': '0.9679', 'eval_runtime': '1.389', 'eval_samples_per_second': '286.5', 'eval_steps_per_second': '18', 'epoch': '4'}
Fold 3 done: acc=0.9673 f1=0.9679 time=84.4s

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3912', 'grad_norm': '11.97', 'learning_rate': '1.742e-05', 'epoch': '0.5263'}
{'eval_loss': '0.1243', 'eval_accuracy': '0.9643', 'eval_precision': '0.9353', 'eval_recall': '0.9641', 'eval_f1': '0.9495', 'eval_runtime': '1.978', 'eval_samples_per_second': '283.6', 'eval_steps_per_second': '18.2', 'epoch': '1'}
{'loss': '0.1427', 'grad_norm': '1.395', 'learning_rate': '1.479e-05', 'epoch': '1.053'}
{'loss': '0.05835', 'grad_norm': '88.64', 'learning_rate': '1.216e-05', 'epoch': '1.579'}
{'eval_loss': '0.1312', 'eval_accuracy': '0.9768', 'eval_precision': '0.984', 'eval_recall': '0.9487', 'eval_f1': '0.9661', 'eval_runtime': '1.988', 'eval_samples_per_second': '282.2', 'eval_steps_per_second': '18.11', 'epoch': '2'}
{'loss': '0.073', 'grad_norm': '0.01928', 'learning_rate': '9.526e-06', 'epoch': '2.105'}
{'loss': '0.02215', 'grad_norm': '18.89', 'learning_rate': '6.895e-06', 'epoch': '2.632'}
{'eval_loss': '0.1379', 'eval_accuracy': '0.9733', 'eval_precision': '0.9688', 'eval_recall': '0.9538', 'eval_f1': '0.9612', 'eval_runtime': '1.984', 'eval_samples_per_second': '282.8', 'eval_steps_per_second': '18.14', 'epoch': '3'}
{'loss': '0.03611', 'grad_norm': '0.02651', 'learning_rate': '4.263e-06', 'epoch': '3.158'}
{'loss': '0.007323', 'grad_norm': '0.0112', 'learning_rate': '1.632e-06', 'epoch': '3.684'}
{'eval_loss': '0.1451', 'eval_accuracy': '0.9768', 'eval_precision': '0.974', 'eval_recall': '0.959', 'eval_f1': '0.9664', 'eval_runtime': '2.007', 'eval_samples_per_second': '279.5', 'eval_steps_per_second': '17.94', 'epoch': '4'}
{'train_runtime': '79', 'train_samples_per_second': '76.46', 'train_steps_per_second': '4.81', 'train_loss': '0.09622', 'epoch': '4'}
{'eval_loss': '0.1451', 'eval_accuracy': '0.9768', 'eval_precision': '0.974', 'eval_recall': '0.959', 'eval_f1': '0.9664', 'eval_runtime': '1.976', 'eval_samples_per_second': '283.9', 'eval_steps_per_second': '18.22', 'epoch': '4'}
Fold 4 done: acc=0.9768 f1=0.9664 time=79.3s

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3921', 'grad_norm': '33.01', 'learning_rate': '1.773e-05', 'epoch': '0.463'}
{'loss': '0.1757', 'grad_norm': '15.31', 'learning_rate': '1.542e-05', 'epoch': '0.9259'}
{'eval_loss': '0.1004', 'eval_accuracy': '0.9688', 'eval_precision': '0.9851', 'eval_recall': '0.9614', 'eval_f1': '0.9731', 'eval_runtime': '1.277', 'eval_samples_per_second': '276.3', 'eval_steps_per_second': '18', 'epoch': '1'}
{'loss': '0.1272', 'grad_norm': '6.776', 'learning_rate': '1.31e-05', 'epoch': '1.389'}
{'loss': '0.06844', 'grad_norm': '54.64', 'learning_rate': '1.079e-05', 'epoch': '1.852'}
{'eval_loss': '0.1203', 'eval_accuracy': '0.9717', 'eval_precision': '0.9805', 'eval_recall': '0.971', 'eval_f1': '0.9757', 'eval_runtime': '1.258', 'eval_samples_per_second': '280.7', 'eval_steps_per_second': '18.29', 'epoch': '2'}
{'loss': '0.04762', 'grad_norm': '71.65', 'learning_rate': '8.472e-06', 'epoch': '2.315'}
{'loss': '0.04356', 'grad_norm': '0.1077', 'learning_rate': '6.157e-06', 'epoch': '2.778'}
{'eval_loss': '0.1254', 'eval_accuracy': '0.9688', 'eval_precision': '0.9804', 'eval_recall': '0.9662', 'eval_f1': '0.9732', 'eval_runtime': '1.255', 'eval_samples_per_second': '281.3', 'eval_steps_per_second': '18.33', 'epoch': '3'}
{'loss': '0.04363', 'grad_norm': '0.08255', 'learning_rate': '3.843e-06', 'epoch': '3.241'}
{'loss': '0.01564', 'grad_norm': '0.6835', 'learning_rate': '1.528e-06', 'epoch': '3.704'}
{'eval_loss': '0.1568', 'eval_accuracy': '0.9688', 'eval_precision': '0.9804', 'eval_recall': '0.9662', 'eval_f1': '0.9732', 'eval_runtime': '1.26', 'eval_samples_per_second': '280.2', 'eval_steps_per_second': '18.26', 'epoch': '4'}
{'train_runtime': '85.98', 'train_samples_per_second': '79.93', 'train_steps_per_second': '5.025', 'train_loss': '0.109', 'epoch': '4'}
{'eval_loss': '0.1568', 'eval_accuracy': '0.9688', 'eval_precision': '0.9804', 'eval_recall': '0.9662', 'eval_f1': '0.9732', 'eval_runtime': '1.245', 'eval_samples_per_second': '283.6', 'eval_steps_per_second': '18.48', 'epoch': '4'}
Fold 5 done: acc=0.9688 f1=0.9732 time=86.3s

RoBERTa-base Mean accuracy: 0.9684 (std 0.0046)
RoBERTa-base Mean f1:       0.9683 (std 0.0026)
RoBERTa-base Mean train time per fold: 84.2s

In [20]:
from transformers import RobertaForSequenceClassification

roberta_large_tok = AutoTokenizer.from_pretrained("roberta-large")

roberta_large_encodings = roberta_large_tok(
    list(df["text"]),
    padding="max_length",
    truncation=True,
    max_length=MAX_LENGTH,
)

roberta_large_dataset = DarkPatternDataset(roberta_large_encodings, list(df["label"]))

large_fold_metrics = []

for FOLD in range(1, 6):
    train_idx = df.index[(df["split"] == "trainval") & (df["cv_fold"] != FOLD)].tolist()
    val_idx   = df.index[(df["split"] == "trainval") & (df["cv_fold"] == FOLD)].tolist()

    train_dataset = Subset(roberta_large_dataset, train_idx)
    val_dataset   = Subset(roberta_large_dataset, val_idx)

    model = RobertaForSequenceClassification.from_pretrained("roberta-large", num_labels=2)

    training_args = TrainingArguments(
        output_dir=f"./roberta_large_fold{FOLD}_output",
        num_train_epochs=4,
        per_device_train_batch_size=8,       # halved vs base, to fit memory
        gradient_accumulation_steps=2,        # 8 x 2 = effective batch size 16, same as every other model
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        seed=42,
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=50,
        report_to="none",
        disable_tqdm=True,
        fp16=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
    )

    start = time.time()
    trainer.train()
    elapsed = time.time() - start

    metrics = trainer.evaluate()
    metrics["fold"] = FOLD
    metrics["train_time_sec"] = elapsed
    large_fold_metrics.append(metrics)
    print(f"Fold {FOLD} done: acc={metrics['eval_accuracy']:.4f} f1={metrics['eval_f1']:.4f} time={elapsed:.1f}s")

acc = [m["eval_accuracy"] for m in large_fold_metrics]
f1 = [m["eval_f1"] for m in large_fold_metrics]
times = [m["train_time_sec"] for m in large_fold_metrics]

print()
print(f"RoBERTa-large Mean accuracy: {np.mean(acc):.4f} (std {np.std(acc):.4f})")
print(f"RoBERTa-large Mean f1:       {np.mean(f1):.4f} (std {np.std(f1):.4f})")
print(f"RoBERTa-large Mean train time per fold: {np.mean(times):.1f}s")

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.42GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.954', 'grad_norm': '167.2', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.4097', 'grad_norm': '113.4', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.1592', 'eval_accuracy': '0.9656', 'eval_precision': '0.9561', 'eval_recall': '0.98', 'eval_f1': '0.9679', 'eval_runtime': '1.251', 'eval_samples_per_second': '302.1', 'eval_steps_per_second': '19.18', 'epoch': '1'}
{'loss': '0.3037', 'grad_norm': '38.01', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.2241', 'grad_norm': '87.57', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1465', 'eval_accuracy': '0.9788', 'eval_precision': '0.98', 'eval_recall': '0.98', 'eval_f1': '0.98', 'eval_runtime': '1.207', 'eval_samples_per_second': '313.2', 'eval_steps_per_second': '19.89', 'epoch': '2'}
{'loss': '0.1105', 'grad_norm': '0.1187', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.09387', 'grad_norm': '30.39', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.135', 'eval_accuracy': '0.9788', 'eval_precision': '0.9752', 'eval_recall': '0.985', 'eval_f1': '0.9801', 'eval_runtime': '1.207', 'eval_samples_per_second': '313.1', 'eval_steps_per_second': '19.88', 'epoch': '3'}
{'loss': '0.1129', 'grad_norm': '0.04717', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.06638', 'grad_norm': '0.02023', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.127', 'eval_accuracy': '0.9788', 'eval_precision': '0.9752', 'eval_recall': '0.985', 'eval_f1': '0.9801', 'eval_runtime': '1.209', 'eval_samples_per_second': '312.7', 'eval_steps_per_second': '19.85', 'epoch': '4'}
{'train_runtime': '119.7', 'train_samples_per_second': '56.57', 'train_steps_per_second': '3.542', 'train_loss': '0.2694', 'epoch': '4'}
{'eval_loss': '0.127', 'eval_accuracy': '0.9788', 'eval_precision': '0.9752', 'eval_recall': '0.985', 'eval_f1': '0.9801', 'eval_runtime': '1.148', 'eval_samples_per_second': '329.3', 'eval_steps_per_second': '20.91', 'epoch': '4'}
Fold 1 done: acc=0.9788 f1=0.9801 time=120.1s

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '1.024', 'grad_norm': '6.926', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.4317', 'grad_norm': '205.6', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.305', 'eval_accuracy': '0.9501', 'eval_precision': '0.9269', 'eval_recall': '0.9854', 'eval_f1': '0.9553', 'eval_runtime': '1.215', 'eval_samples_per_second': '313.5', 'eval_steps_per_second': '19.75', 'epoch': '1'}
{'loss': '0.2782', 'grad_norm': '1.666', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.2856', 'grad_norm': '15.27', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1152', 'eval_accuracy': '0.9764', 'eval_precision': '0.99', 'eval_recall': '0.966', 'eval_f1': '0.9779', 'eval_runtime': '1.215', 'eval_samples_per_second': '313.6', 'eval_steps_per_second': '19.75', 'epoch': '2'}
{'loss': '0.1476', 'grad_norm': '0.129', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.1445', 'grad_norm': '244.3', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1349', 'eval_accuracy': '0.9711', 'eval_precision': '0.971', 'eval_recall': '0.9757', 'eval_f1': '0.9734', 'eval_runtime': '1.209', 'eval_samples_per_second': '315.2', 'eval_steps_per_second': '19.85', 'epoch': '3'}
{'loss': '0.0256', 'grad_norm': '0.01546', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.05458', 'grad_norm': '0.004936', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.1264', 'eval_accuracy': '0.9764', 'eval_precision': '0.9852', 'eval_recall': '0.9709', 'eval_f1': '0.978', 'eval_runtime': '1.208', 'eval_samples_per_second': '315.4', 'eval_steps_per_second': '19.87', 'epoch': '4'}
{'train_runtime': '119.7', 'train_samples_per_second': '56.48', 'train_steps_per_second': '3.542', 'train_loss': '0.2913', 'epoch': '4'}
{'eval_loss': '0.1264', 'eval_accuracy': '0.9764', 'eval_precision': '0.9852', 'eval_recall': '0.9709', 'eval_f1': '0.978', 'eval_runtime': '1.23', 'eval_samples_per_second': '309.8', 'eval_steps_per_second': '19.52', 'epoch': '4'}
Fold 2 done: acc=0.9764 f1=0.9780 time=120.2s

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.9752', 'grad_norm': '72.24', 'learning_rate': '1.767e-05', 'epoch': '0.4762'}
{'loss': '0.3574', 'grad_norm': '1.35', 'learning_rate': '1.529e-05', 'epoch': '0.9524'}
{'eval_loss': '0.2585', 'eval_accuracy': '0.9497', 'eval_precision': '0.9378', 'eval_recall': '0.9655', 'eval_f1': '0.9515', 'eval_runtime': '1.283', 'eval_samples_per_second': '310.2', 'eval_steps_per_second': '19.48', 'epoch': '1'}
{'loss': '0.338', 'grad_norm': '37.9', 'learning_rate': '1.29e-05', 'epoch': '1.429'}
{'loss': '0.2789', 'grad_norm': '0.4829', 'learning_rate': '1.052e-05', 'epoch': '1.905'}
{'eval_loss': '0.1635', 'eval_accuracy': '0.9673', 'eval_precision': '0.9847', 'eval_recall': '0.9507', 'eval_f1': '0.9674', 'eval_runtime': '1.3', 'eval_samples_per_second': '306.2', 'eval_steps_per_second': '19.23', 'epoch': '2'}
{'loss': '0.1072', 'grad_norm': '0.1689', 'learning_rate': '8.143e-06', 'epoch': '2.381'}
{'loss': '0.2041', 'grad_norm': '0.1958', 'learning_rate': '5.762e-06', 'epoch': '2.857'}
{'eval_loss': '0.1314', 'eval_accuracy': '0.9724', 'eval_precision': '0.9752', 'eval_recall': '0.9704', 'eval_f1': '0.9728', 'eval_runtime': '1.271', 'eval_samples_per_second': '313.2', 'eval_steps_per_second': '19.67', 'epoch': '3'}
{'loss': '0.07969', 'grad_norm': '0.04056', 'learning_rate': '3.381e-06', 'epoch': '3.333'}
{'loss': '0.05071', 'grad_norm': '59.91', 'learning_rate': '1e-06', 'epoch': '3.81'}
{'eval_loss': '0.1505', 'eval_accuracy': '0.9749', 'eval_precision': '0.9801', 'eval_recall': '0.9704', 'eval_f1': '0.9752', 'eval_runtime': '1.275', 'eval_samples_per_second': '312.1', 'eval_steps_per_second': '19.6', 'epoch': '4'}
{'train_runtime': '121', 'train_samples_per_second': '55.29', 'train_steps_per_second': '3.47', 'train_loss': '0.2904', 'epoch': '4'}
{'eval_loss': '0.1505', 'eval_accuracy': '0.9749', 'eval_precision': '0.9801', 'eval_recall': '0.9704', 'eval_f1': '0.9752', 'eval_runtime': '1.238', 'eval_samples_per_second': '321.6', 'eval_steps_per_second': '20.2', 'epoch': '4'}
Fold 3 done: acc=0.9749 f1=0.9752 time=121.5s

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.9736', 'grad_norm': 'inf', 'learning_rate': '1.742e-05', 'epoch': '0.5291'}
{'eval_loss': '0.2648', 'eval_accuracy': '0.943', 'eval_precision': '0.8688', 'eval_recall': '0.9846', 'eval_f1': '0.9231', 'eval_runtime': '1.786', 'eval_samples_per_second': '314', 'eval_steps_per_second': '20.15', 'epoch': '1'}
{'loss': '0.3584', 'grad_norm': '0.4419', 'learning_rate': '1.479e-05', 'epoch': '1.053'}
{'loss': '0.295', 'grad_norm': '18.43', 'learning_rate': '1.216e-05', 'epoch': '1.582'}
{'eval_loss': '0.1634', 'eval_accuracy': '0.975', 'eval_precision': '0.9892', 'eval_recall': '0.9385', 'eval_f1': '0.9632', 'eval_runtime': '1.792', 'eval_samples_per_second': '313.1', 'eval_steps_per_second': '20.09', 'epoch': '2'}
{'loss': '0.2103', 'grad_norm': '0.09288', 'learning_rate': '9.526e-06', 'epoch': '2.106'}
{'loss': '0.1034', 'grad_norm': '0.764', 'learning_rate': '6.895e-06', 'epoch': '2.635'}
{'eval_loss': '0.1835', 'eval_accuracy': '0.9679', 'eval_precision': '0.9538', 'eval_recall': '0.9538', 'eval_f1': '0.9538', 'eval_runtime': '1.785', 'eval_samples_per_second': '314.3', 'eval_steps_per_second': '20.17', 'epoch': '3'}
{'loss': '0.12', 'grad_norm': '15.54', 'learning_rate': '4.263e-06', 'epoch': '3.159'}
{'loss': '0.01662', 'grad_norm': '0.01779', 'learning_rate': '1.632e-06', 'epoch': '3.688'}
{'eval_loss': '0.2052', 'eval_accuracy': '0.9715', 'eval_precision': '0.959', 'eval_recall': '0.959', 'eval_f1': '0.959', 'eval_runtime': '1.785', 'eval_samples_per_second': '314.3', 'eval_steps_per_second': '20.17', 'epoch': '4'}
{'train_runtime': '110.8', 'train_samples_per_second': '54.52', 'train_steps_per_second': '3.43', 'train_loss': '0.2775', 'epoch': '4'}
{'eval_loss': '0.2052', 'eval_accuracy': '0.9715', 'eval_precision': '0.959', 'eval_recall': '0.959', 'eval_f1': '0.959', 'eval_runtime': '1.773', 'eval_samples_per_second': '316.5', 'eval_steps_per_second': '20.31', 'epoch': '4'}
Fold 4 done: acc=0.9715 f1=0.9590 time=111.4s

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.8688', 'grad_norm': '64.25', 'learning_rate': '1.773e-05', 'epoch': '0.4651'}
{'loss': '0.5086', 'grad_norm': '98.2', 'learning_rate': '1.542e-05', 'epoch': '0.9302'}
{'eval_loss': '0.26', 'eval_accuracy': '0.9462', 'eval_precision': '0.9273', 'eval_recall': '0.9855', 'eval_f1': '0.9555', 'eval_runtime': '1.161', 'eval_samples_per_second': '304.1', 'eval_steps_per_second': '19.81', 'epoch': '1'}
{'loss': '0.4732', 'grad_norm': '128.6', 'learning_rate': '1.31e-05', 'epoch': '1.391'}
{'loss': '0.168', 'grad_norm': '0.1189', 'learning_rate': '1.079e-05', 'epoch': '1.856'}
{'eval_loss': '0.2616', 'eval_accuracy': '0.9518', 'eval_precision': '0.9398', 'eval_recall': '0.9807', 'eval_f1': '0.9598', 'eval_runtime': '1.187', 'eval_samples_per_second': '297.4', 'eval_steps_per_second': '19.38', 'epoch': '2'}
{'loss': '0.1696', 'grad_norm': '0.07159', 'learning_rate': '8.472e-06', 'epoch': '2.316'}
{'loss': '0.1023', 'grad_norm': '0.01199', 'learning_rate': '6.157e-06', 'epoch': '2.781'}
{'eval_loss': '0.1805', 'eval_accuracy': '0.9745', 'eval_precision': '0.9806', 'eval_recall': '0.9758', 'eval_f1': '0.9782', 'eval_runtime': '1.154', 'eval_samples_per_second': '305.8', 'eval_steps_per_second': '19.92', 'epoch': '3'}
{'loss': '0.08258', 'grad_norm': '0.01637', 'learning_rate': '3.843e-06', 'epoch': '3.242'}
{'loss': '0.02913', 'grad_norm': '0.005436', 'learning_rate': '1.528e-06', 'epoch': '3.707'}
{'eval_loss': '0.1969', 'eval_accuracy': '0.9717', 'eval_precision': '0.9805', 'eval_recall': '0.971', 'eval_f1': '0.9757', 'eval_runtime': '1.16', 'eval_samples_per_second': '304.3', 'eval_steps_per_second': '19.82', 'epoch': '4'}
{'train_runtime': '122.5', 'train_samples_per_second': '56.09', 'train_steps_per_second': '3.526', 'train_loss': '0.2829', 'epoch': '4'}
{'eval_loss': '0.1969', 'eval_accuracy': '0.9717', 'eval_precision': '0.9805', 'eval_recall': '0.971', 'eval_f1': '0.9757', 'eval_runtime': '1.117', 'eval_samples_per_second': '316.1', 'eval_steps_per_second': '20.6', 'epoch': '4'}
Fold 5 done: acc=0.9717 f1=0.9757 time=123.1s

RoBERTa-large Mean accuracy: 0.9746 (std 0.0028)
RoBERTa-large Mean f1:       0.9736 (std 0.0075)
RoBERTa-large Mean train time per fold: 119.2s

In [21]:
import torch
import time
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from transformers import DistilBertForSequenceClassification, RobertaForSequenceClassification, Trainer, TrainingArguments

# ---------- SECTION 13: Error analysis via out-of-fold predictions ----------

def run_cv_with_predictions(model_class, model_name, dataset, is_large=False):
    all_preds = []
    for FOLD in range(1, 6):
        train_idx = df.index[(df["split"] == "trainval") & (df["cv_fold"] != FOLD)].tolist()
        val_idx   = df.index[(df["split"] == "trainval") & (df["cv_fold"] == FOLD)].tolist()

        train_dataset = Subset(dataset, train_idx)
        val_dataset   = Subset(dataset, val_idx)

        model = model_class.from_pretrained(model_name, num_labels=2)

        training_args = TrainingArguments(
            output_dir=f"./tmp_{model_name.replace('/', '_')}_fold{FOLD}",
            num_train_epochs=4,
            per_device_train_batch_size=8 if is_large else 16,
            gradient_accumulation_steps=2 if is_large else 1,
            per_device_eval_batch_size=16,
            learning_rate=2e-5,
            seed=42,
            eval_strategy="no",
            save_strategy="no",
            logging_steps=200,
            report_to="none",
            disable_tqdm=True,
            fp16=True,
        )

        trainer = Trainer(model=model, args=training_args, train_dataset=train_dataset)
        trainer.train()

        pred_output = trainer.predict(val_dataset)
        pred_labels = np.argmax(pred_output.predictions, axis=1)
        probs = torch.softmax(torch.tensor(pred_output.predictions), dim=1).numpy()

        fold_df = df.loc[val_idx, ["page_id", "text", "label", "Pattern Category"]].copy()
        fold_df["orig_idx"] = val_idx
        fold_df["predicted"] = pred_labels
        fold_df["confidence"] = probs.max(axis=1)
        fold_df["fold"] = FOLD
        all_preds.append(fold_df)
        print(f"  Fold {FOLD} done.")

    return pd.concat(all_preds, ignore_index=True)

print("Running DistilBERT out-of-fold predictions...")
distil_oof = run_cv_with_predictions(DistilBertForSequenceClassification, "distilbert-base-uncased", distil_dataset)

print("Running RoBERTa-large out-of-fold predictions...")
roberta_large_oof = run_cv_with_predictions(RobertaForSequenceClassification, "roberta-large", roberta_large_dataset, is_large=True)

def error_report(oof_df, name):
    errors = oof_df[oof_df.label != oof_df.predicted]
    print(f"\n=== {name} ===")
    print(f"Error rate: {len(errors)}/{len(oof_df)} = {len(errors)/len(oof_df):.2%}")
    print("Errors by Pattern Category:")
    print(errors["Pattern Category"].value_counts())
    cm = confusion_matrix(oof_df.label, oof_df.predicted)
    print("Confusion matrix [[TN, FP], [FN, TP]]:")
    print(cm)
    return errors

distil_errors = error_report(distil_oof, "DistilBERT")
roberta_errors = error_report(roberta_large_oof, "RoBERTa-large")

# Merge to see overlap: does each model fail on the SAME examples, or different ones?
merged = distil_oof[["orig_idx", "text", "label", "Pattern Category", "predicted"]].rename(columns={"predicted": "distil_pred"})
merged = merged.merge(
    roberta_large_oof[["orig_idx", "predicted"]].rename(columns={"predicted": "roberta_pred"}),
    on="orig_idx"
)
merged["distil_wrong"] = merged["label"] != merged["distil_pred"]
merged["roberta_wrong"] = merged["label"] != merged["roberta_pred"]

both_wrong = merged[merged.distil_wrong & merged.roberta_wrong]
distil_only = merged[merged.distil_wrong & ~merged.roberta_wrong]
roberta_only = merged[~merged.distil_wrong & merged.roberta_wrong]

print(f"\nBoth models wrong: {len(both_wrong)}")
print(f"DistilBERT wrong, RoBERTa-large right: {len(distil_only)}")
print(f"RoBERTa-large wrong, DistilBERT right: {len(roberta_only)}")
print("\nExamples BOTH models got wrong (genuinely hard cases):")
print(both_wrong[["text", "label", "Pattern Category"]].head(10).to_string(index=False))

# ---------- SECTION 14: Computational analysis ----------

def measure_inference(model_class, model_name, tokenizer, device):
    model = model_class.from_pretrained(model_name, num_labels=2).to(device)
    model.eval()
    sample = tokenizer("FLASH SALE | LIMITED TIME ONLY Shop Now", return_tensors="pt",
                        padding="max_length", truncation=True, max_length=MAX_LENGTH).to(device)
    with torch.no_grad():
        for _ in range(10):  # warmup
            _ = model(**sample)
    if device == "cuda":
        torch.cuda.synchronize()
    start = time.time()
    with torch.no_grad():
        for _ in range(100):
            _ = model(**sample)
    if device == "cuda":
        torch.cuda.synchronize()
    elapsed_ms = (time.time() - start) / 100 * 1000
    n_params = model.num_parameters()
    print(f"{model_name:25s} | {device:4s} | {n_params:>12,} params | {elapsed_ms:6.2f} ms/prediction")
    return n_params, elapsed_ms

print("\n=== Inference latency: single text in, one prediction out ===")
for device in ["cuda", "cpu"]:
    measure_inference(BertForSequenceClassification, "bert-base-uncased", tok, device)
    measure_inference(DistilBertForSequenceClassification, "distilbert-base-uncased", distil_tok, device)
    measure_inference(RobertaForSequenceClassification, "roberta-base", roberta_tok, device)
    measure_inference(RobertaForSequenceClassification, "roberta-large", roberta_large_tok, device)

Running DistilBERT out-of-fold predictions...

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.1862', 'grad_norm': '6.869', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'loss': '0.04833', 'grad_norm': '0.05663', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'train_runtime': '17.21', 'train_samples_per_second': '393.5', 'train_steps_per_second': '24.64', 'train_loss': '0.1117', 'epoch': '4'}
  Fold 1 done.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.2015', 'grad_norm': '1.501', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'loss': '0.05096', 'grad_norm': '0.05634', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'train_runtime': '17.29', 'train_samples_per_second': '391', 'train_steps_per_second': '24.52', 'train_loss': '0.1213', 'epoch': '4'}
  Fold 2 done.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.2028', 'grad_norm': '0.2097', 'learning_rate': '1.052e-05', 'epoch': '1.905'}
{'loss': '0.04078', 'grad_norm': '2.507', 'learning_rate': '1e-06', 'epoch': '3.81'}
{'train_runtime': '17.17', 'train_samples_per_second': '389.7', 'train_steps_per_second': '24.46', 'train_loss': '0.1186', 'epoch': '4'}
  Fold 3 done.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.1904', 'grad_norm': '0.4434', 'learning_rate': '9.526e-06', 'epoch': '2.105'}
{'train_runtime': '15.39', 'train_samples_per_second': '392.4', 'train_steps_per_second': '24.69', 'train_loss': '0.1195', 'epoch': '4'}
  Fold 4 done.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.1991', 'grad_norm': '5.205', 'learning_rate': '1.079e-05', 'epoch': '1.852'}
{'loss': '0.04334', 'grad_norm': '6.137', 'learning_rate': '1.528e-06', 'epoch': '3.704'}
{'train_runtime': '17.57', 'train_samples_per_second': '391.1', 'train_steps_per_second': '24.59', 'train_loss': '0.1158', 'epoch': '4'}
  Fold 5 done.
Running RoBERTa-large out-of-fold predictions...

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4456', 'grad_norm': '117.9', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'loss': '0.0872', 'grad_norm': '0.01834', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'train_runtime': '114.9', 'train_samples_per_second': '58.94', 'train_steps_per_second': '3.69', 'train_loss': '0.2514', 'epoch': '4'}
  Fold 1 done.

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4247', 'grad_norm': '21.51', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'loss': '0.09547', 'grad_norm': '0.005233', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'train_runtime': '114', 'train_samples_per_second': '59.27', 'train_steps_per_second': '3.718', 'train_loss': '0.2494', 'epoch': '4'}
  Fold 2 done.

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.3954', 'grad_norm': '158.8', 'learning_rate': '1.052e-05', 'epoch': '1.905'}
{'loss': '0.04802', 'grad_norm': '0.2657', 'learning_rate': '1e-06', 'epoch': '3.81'}
{'train_runtime': '114.5', 'train_samples_per_second': '58.45', 'train_steps_per_second': '3.669', 'train_loss': '0.216', 'epoch': '4'}
  Fold 3 done.

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4232', 'grad_norm': '0.385', 'learning_rate': '9.526e-06', 'epoch': '2.106'}
{'train_runtime': '102.3', 'train_samples_per_second': '59.03', 'train_steps_per_second': '3.714', 'train_loss': '0.2672', 'epoch': '4'}
  Fold 4 done.

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4633', 'grad_norm': '0.03318', 'learning_rate': '1.079e-05', 'epoch': '1.856'}
{'loss': '0.07682', 'grad_norm': '0.006867', 'learning_rate': '1.528e-06', 'epoch': '3.707'}
{'train_runtime': '115.8', 'train_samples_per_second': '59.36', 'train_steps_per_second': '3.732', 'train_loss': '0.2561', 'epoch': '4'}
  Fold 5 done.

=== DistilBERT ===
Error rate: 72/2071 = 3.48%
Errors by Pattern Category:
Pattern Category
Not Dark Pattern    31
Misdirection        26
Scarcity             5
Social Proof         4
Sneaking             3
Urgency              2
Obstruction          1
Name: count, dtype: int64
Confusion matrix [[TN, FP], [FN, TP]]:
[[1029   31]
 [  41  970]]

=== RoBERTa-large ===
Error rate: 45/2071 = 2.17%
Errors by Pattern Category:
Pattern Category
Not Dark Pattern    23
Misdirection        14
Social Proof         3
Scarcity             2
Sneaking             2
Urgency              1
Name: count, dtype: int64
Confusion matrix [[TN, FP], [FN, TP]]:
[[1037   23]
 [  22  989]]

Both models wrong: 24
DistilBERT wrong, RoBERTa-large right: 48
RoBERTa-large wrong, DistilBERT right: 21

Examples BOTH models got wrong (genuinely hard cases):
                                                                       text  label Pattern Category
                                        SUBSCRIPTION SUCCESSFUL. THANK YOU!      0 Not Dark Pattern
                                 Sorry! This product is no longer available      0 Not Dark Pattern
                                                           How about these?      1     Misdirection
                                                      Personalize your doll      1     Misdirection
                                                   Grab yourself a bargain!      1     Misdirection
                                    Before you check out, can we tempt you?      1     Misdirection
                                                             LOGIN/REGISTER      1     Misdirection
                          Let's make sure you have everything else you need      1     Misdirection
                                                       Lenscap: Damage Only      1     Misdirection
Our most recent customers are from New Rochelle, Roseville, and Brooksville      1     Social Proof

=== Inference latency: single text in, one prediction out ===

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

bert-base-uncased         | cuda |  109,483,778 params |   9.01 ms/prediction

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

distilbert-base-uncased   | cuda |   66,955,010 params |   4.78 ms/prediction

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

roberta-base              | cuda |  124,647,170 params |   9.55 ms/prediction

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

roberta-large             | cuda |  355,361,794 params |  18.87 ms/prediction

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

bert-base-uncased         | cpu  |  109,483,778 params | 172.97 ms/prediction

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

distilbert-base-uncased   | cpu  |   66,955,010 params |  90.29 ms/prediction

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

roberta-base              | cpu  |  124,647,170 params | 170.27 ms/prediction

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

roberta-large             | cpu  |  355,361,794 params | 998.17 ms/prediction

In [22]:
import copy
from transformers import TrainerCallback

class BestModelTracker(TrainerCallback):
    """Keeps the best-F1 epoch's weights in memory. No disk writes during training."""
    def __init__(self):
        self.best_f1 = -1
        self.best_state_dict = None
        self.best_epoch = None

    def on_evaluate(self, args, state, control, metrics, model, **kwargs):
        f1 = metrics.get("eval_f1", -1)
        if f1 > self.best_f1:
            self.best_f1 = f1
            self.best_epoch = state.epoch
            # copy weights to CPU so GPU memory isn't doubled
            self.best_state_dict = copy.deepcopy({k: v.cpu() for k, v in model.state_dict().items()})

large_fold_metrics_earlystop = []
best_epochs_used = []

for FOLD in range(1, 6):
    train_idx = df.index[(df["split"] == "trainval") & (df["cv_fold"] != FOLD)].tolist()
    val_idx   = df.index[(df["split"] == "trainval") & (df["cv_fold"] == FOLD)].tolist()

    train_dataset = Subset(roberta_large_dataset, train_idx)
    val_dataset   = Subset(roberta_large_dataset, val_idx)

    model = RobertaForSequenceClassification.from_pretrained("roberta-large", num_labels=2)
    tracker = BestModelTracker()

    training_args = TrainingArguments(
        output_dir=f"./roberta_large_es_fold{FOLD}",
        num_train_epochs=4,
        per_device_train_batch_size=8,
        gradient_accumulation_steps=2,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        seed=42,
        eval_strategy="epoch",
        save_strategy="no",          # <-- key fix: never write checkpoints to disk
        logging_steps=50,
        report_to="none",
        disable_tqdm=True,
        fp16=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        callbacks=[tracker],
    )

    trainer.train()

    # reload the best epoch's weights (from memory, instant) before final scoring
    model.load_state_dict(tracker.best_state_dict)
    metrics = trainer.evaluate()
    metrics["fold"] = FOLD
    large_fold_metrics_earlystop.append(metrics)
    best_epochs_used.append(tracker.best_epoch)

    print(f"Fold {FOLD}: acc={metrics['eval_accuracy']:.4f} f1={metrics['eval_f1']:.4f} best_epoch={tracker.best_epoch}")

acc = [m["eval_accuracy"] for m in large_fold_metrics_earlystop]
f1 = [m["eval_f1"] for m in large_fold_metrics_earlystop]

print()
print(f"Early-stopped RoBERTa-large Mean accuracy: {np.mean(acc):.4f} (std {np.std(acc):.4f})")
print(f"Early-stopped RoBERTa-large Mean f1:       {np.mean(f1):.4f} (std {np.std(f1):.4f})")
print("Best epoch per fold:", best_epochs_used)
print()
print("Compare to fixed-4-epoch result: accuracy=0.9746, f1=0.9736")

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.6533', 'grad_norm': '10.84', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.3948', 'grad_norm': '6.786', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.1385', 'eval_accuracy': '0.9603', 'eval_precision': '0.9843', 'eval_recall': '0.94', 'eval_f1': '0.9616', 'eval_runtime': '1.167', 'eval_samples_per_second': '323.8', 'eval_steps_per_second': '20.56', 'epoch': '1'}
{'loss': '0.2889', 'grad_norm': '52.99', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.2276', 'grad_norm': '172.5', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.122', 'eval_accuracy': '0.9788', 'eval_precision': '0.9848', 'eval_recall': '0.975', 'eval_f1': '0.9799', 'eval_runtime': '1.177', 'eval_samples_per_second': '321.1', 'eval_steps_per_second': '20.39', 'epoch': '2'}
{'loss': '0.1344', 'grad_norm': '0.5272', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.06059', 'grad_norm': '1.898', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1254', 'eval_accuracy': '0.9815', 'eval_precision': '0.9801', 'eval_recall': '0.985', 'eval_f1': '0.9825', 'eval_runtime': '1.225', 'eval_samples_per_second': '308.5', 'eval_steps_per_second': '19.59', 'epoch': '3'}
{'loss': '0.08691', 'grad_norm': '0.02301', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.04393', 'grad_norm': '0.01304', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.1467', 'eval_accuracy': '0.9762', 'eval_precision': '0.9659', 'eval_recall': '0.99', 'eval_f1': '0.9778', 'eval_runtime': '1.186', 'eval_samples_per_second': '318.8', 'eval_steps_per_second': '20.24', 'epoch': '4'}
{'train_runtime': '123.7', 'train_samples_per_second': '54.74', 'train_steps_per_second': '3.427', 'train_loss': '0.2248', 'epoch': '4'}
{'eval_loss': '0.1254', 'eval_accuracy': '0.9815', 'eval_precision': '0.9801', 'eval_recall': '0.985', 'eval_f1': '0.9825', 'eval_runtime': '1.136', 'eval_samples_per_second': '332.7', 'eval_steps_per_second': '21.12', 'epoch': '4'}
Fold 1: acc=0.9815 f1=0.9825 best_epoch=3.0

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '1.024', 'grad_norm': '6.926', 'learning_rate': '1.769e-05', 'epoch': '0.4717'}
{'loss': '0.4317', 'grad_norm': '205.6', 'learning_rate': '1.533e-05', 'epoch': '0.9434'}
{'eval_loss': '0.305', 'eval_accuracy': '0.9501', 'eval_precision': '0.9269', 'eval_recall': '0.9854', 'eval_f1': '0.9553', 'eval_runtime': '1.236', 'eval_samples_per_second': '308.4', 'eval_steps_per_second': '19.43', 'epoch': '1'}
{'loss': '0.2782', 'grad_norm': '1.666', 'learning_rate': '1.297e-05', 'epoch': '1.415'}
{'loss': '0.2856', 'grad_norm': '15.27', 'learning_rate': '1.061e-05', 'epoch': '1.887'}
{'eval_loss': '0.1152', 'eval_accuracy': '0.9764', 'eval_precision': '0.99', 'eval_recall': '0.966', 'eval_f1': '0.9779', 'eval_runtime': '1.201', 'eval_samples_per_second': '317.1', 'eval_steps_per_second': '19.98', 'epoch': '2'}
{'loss': '0.1476', 'grad_norm': '0.129', 'learning_rate': '8.255e-06', 'epoch': '2.358'}
{'loss': '0.1445', 'grad_norm': '244.3', 'learning_rate': '5.896e-06', 'epoch': '2.83'}
{'eval_loss': '0.1349', 'eval_accuracy': '0.9711', 'eval_precision': '0.971', 'eval_recall': '0.9757', 'eval_f1': '0.9734', 'eval_runtime': '1.214', 'eval_samples_per_second': '313.9', 'eval_steps_per_second': '19.77', 'epoch': '3'}
{'loss': '0.0256', 'grad_norm': '0.01546', 'learning_rate': '3.538e-06', 'epoch': '3.302'}
{'loss': '0.05458', 'grad_norm': '0.004936', 'learning_rate': '1.179e-06', 'epoch': '3.774'}
{'eval_loss': '0.1264', 'eval_accuracy': '0.9764', 'eval_precision': '0.9852', 'eval_recall': '0.9709', 'eval_f1': '0.978', 'eval_runtime': '1.171', 'eval_samples_per_second': '325.5', 'eval_steps_per_second': '20.5', 'epoch': '4'}
{'train_runtime': '125.3', 'train_samples_per_second': '53.94', 'train_steps_per_second': '3.383', 'train_loss': '0.2913', 'epoch': '4'}
{'eval_loss': '0.1264', 'eval_accuracy': '0.9764', 'eval_precision': '0.9852', 'eval_recall': '0.9709', 'eval_f1': '0.978', 'eval_runtime': '1.154', 'eval_samples_per_second': '330.2', 'eval_steps_per_second': '20.8', 'epoch': '4'}
Fold 2: acc=0.9764 f1=0.9780 best_epoch=4.0

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.9752', 'grad_norm': '72.24', 'learning_rate': '1.767e-05', 'epoch': '0.4762'}
{'loss': '0.3574', 'grad_norm': '1.35', 'learning_rate': '1.529e-05', 'epoch': '0.9524'}
{'eval_loss': '0.2585', 'eval_accuracy': '0.9497', 'eval_precision': '0.9378', 'eval_recall': '0.9655', 'eval_f1': '0.9515', 'eval_runtime': '1.27', 'eval_samples_per_second': '313.4', 'eval_steps_per_second': '19.69', 'epoch': '1'}
{'loss': '0.338', 'grad_norm': '37.9', 'learning_rate': '1.29e-05', 'epoch': '1.429'}
{'loss': '0.2789', 'grad_norm': '0.4829', 'learning_rate': '1.052e-05', 'epoch': '1.905'}
{'eval_loss': '0.1635', 'eval_accuracy': '0.9673', 'eval_precision': '0.9847', 'eval_recall': '0.9507', 'eval_f1': '0.9674', 'eval_runtime': '1.265', 'eval_samples_per_second': '314.6', 'eval_steps_per_second': '19.76', 'epoch': '2'}
{'loss': '0.1072', 'grad_norm': '0.1689', 'learning_rate': '8.143e-06', 'epoch': '2.381'}
{'loss': '0.2041', 'grad_norm': '0.1958', 'learning_rate': '5.762e-06', 'epoch': '2.857'}
{'eval_loss': '0.1314', 'eval_accuracy': '0.9724', 'eval_precision': '0.9752', 'eval_recall': '0.9704', 'eval_f1': '0.9728', 'eval_runtime': '1.272', 'eval_samples_per_second': '313', 'eval_steps_per_second': '19.66', 'epoch': '3'}
{'loss': '0.07969', 'grad_norm': '0.04056', 'learning_rate': '3.381e-06', 'epoch': '3.333'}
{'loss': '0.05071', 'grad_norm': '59.91', 'learning_rate': '1e-06', 'epoch': '3.81'}
{'eval_loss': '0.1505', 'eval_accuracy': '0.9749', 'eval_precision': '0.9801', 'eval_recall': '0.9704', 'eval_f1': '0.9752', 'eval_runtime': '1.258', 'eval_samples_per_second': '316.4', 'eval_steps_per_second': '19.87', 'epoch': '4'}
{'train_runtime': '121.1', 'train_samples_per_second': '55.27', 'train_steps_per_second': '3.469', 'train_loss': '0.2904', 'epoch': '4'}
{'eval_loss': '0.1505', 'eval_accuracy': '0.9749', 'eval_precision': '0.9801', 'eval_recall': '0.9704', 'eval_f1': '0.9752', 'eval_runtime': '1.191', 'eval_samples_per_second': '334.2', 'eval_steps_per_second': '20.99', 'epoch': '4'}
Fold 3: acc=0.9749 f1=0.9752 best_epoch=4.0

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.9736', 'grad_norm': 'inf', 'learning_rate': '1.742e-05', 'epoch': '0.5291'}
{'eval_loss': '0.2648', 'eval_accuracy': '0.943', 'eval_precision': '0.8688', 'eval_recall': '0.9846', 'eval_f1': '0.9231', 'eval_runtime': '1.792', 'eval_samples_per_second': '313.1', 'eval_steps_per_second': '20.09', 'epoch': '1'}
{'loss': '0.3584', 'grad_norm': '0.4419', 'learning_rate': '1.479e-05', 'epoch': '1.053'}
{'loss': '0.295', 'grad_norm': '18.43', 'learning_rate': '1.216e-05', 'epoch': '1.582'}
{'eval_loss': '0.1634', 'eval_accuracy': '0.975', 'eval_precision': '0.9892', 'eval_recall': '0.9385', 'eval_f1': '0.9632', 'eval_runtime': '1.772', 'eval_samples_per_second': '316.6', 'eval_steps_per_second': '20.32', 'epoch': '2'}
{'loss': '0.2103', 'grad_norm': '0.09288', 'learning_rate': '9.526e-06', 'epoch': '2.106'}
{'loss': '0.1034', 'grad_norm': '0.764', 'learning_rate': '6.895e-06', 'epoch': '2.635'}
{'eval_loss': '0.1835', 'eval_accuracy': '0.9679', 'eval_precision': '0.9538', 'eval_recall': '0.9538', 'eval_f1': '0.9538', 'eval_runtime': '1.776', 'eval_samples_per_second': '315.8', 'eval_steps_per_second': '20.27', 'epoch': '3'}
{'loss': '0.12', 'grad_norm': '15.54', 'learning_rate': '4.263e-06', 'epoch': '3.159'}
{'loss': '0.01662', 'grad_norm': '0.01779', 'learning_rate': '1.632e-06', 'epoch': '3.688'}
{'eval_loss': '0.2052', 'eval_accuracy': '0.9715', 'eval_precision': '0.959', 'eval_recall': '0.959', 'eval_f1': '0.959', 'eval_runtime': '1.772', 'eval_samples_per_second': '316.6', 'eval_steps_per_second': '20.31', 'epoch': '4'}
{'train_runtime': '110.4', 'train_samples_per_second': '54.69', 'train_steps_per_second': '3.441', 'train_loss': '0.2775', 'epoch': '4'}
{'eval_loss': '0.1634', 'eval_accuracy': '0.975', 'eval_precision': '0.9892', 'eval_recall': '0.9385', 'eval_f1': '0.9632', 'eval_runtime': '1.747', 'eval_samples_per_second': '321.2', 'eval_steps_per_second': '20.61', 'epoch': '4'}
Fold 4: acc=0.9750 f1=0.9632 best_epoch=2.0

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.8688', 'grad_norm': '64.25', 'learning_rate': '1.773e-05', 'epoch': '0.4651'}
{'loss': '0.5086', 'grad_norm': '98.2', 'learning_rate': '1.542e-05', 'epoch': '0.9302'}
{'eval_loss': '0.26', 'eval_accuracy': '0.9462', 'eval_precision': '0.9273', 'eval_recall': '0.9855', 'eval_f1': '0.9555', 'eval_runtime': '1.154', 'eval_samples_per_second': '305.8', 'eval_steps_per_second': '19.92', 'epoch': '1'}
{'loss': '0.4732', 'grad_norm': '128.6', 'learning_rate': '1.31e-05', 'epoch': '1.391'}
{'loss': '0.168', 'grad_norm': '0.1189', 'learning_rate': '1.079e-05', 'epoch': '1.856'}
{'eval_loss': '0.2616', 'eval_accuracy': '0.9518', 'eval_precision': '0.9398', 'eval_recall': '0.9807', 'eval_f1': '0.9598', 'eval_runtime': '1.173', 'eval_samples_per_second': '300.9', 'eval_steps_per_second': '19.6', 'epoch': '2'}
{'loss': '0.1696', 'grad_norm': '0.07159', 'learning_rate': '8.472e-06', 'epoch': '2.316'}
{'loss': '0.1023', 'grad_norm': '0.01199', 'learning_rate': '6.157e-06', 'epoch': '2.781'}
{'eval_loss': '0.1805', 'eval_accuracy': '0.9745', 'eval_precision': '0.9806', 'eval_recall': '0.9758', 'eval_f1': '0.9782', 'eval_runtime': '1.147', 'eval_samples_per_second': '307.8', 'eval_steps_per_second': '20.05', 'epoch': '3'}
{'loss': '0.08258', 'grad_norm': '0.01637', 'learning_rate': '3.843e-06', 'epoch': '3.242'}
{'loss': '0.02913', 'grad_norm': '0.005436', 'learning_rate': '1.528e-06', 'epoch': '3.707'}
{'eval_loss': '0.1969', 'eval_accuracy': '0.9717', 'eval_precision': '0.9805', 'eval_recall': '0.971', 'eval_f1': '0.9757', 'eval_runtime': '1.175', 'eval_samples_per_second': '300.4', 'eval_steps_per_second': '19.57', 'epoch': '4'}
{'train_runtime': '121.8', 'train_samples_per_second': '56.42', 'train_steps_per_second': '3.547', 'train_loss': '0.2829', 'epoch': '4'}
{'eval_loss': '0.1805', 'eval_accuracy': '0.9745', 'eval_precision': '0.9806', 'eval_recall': '0.9758', 'eval_f1': '0.9782', 'eval_runtime': '1.118', 'eval_samples_per_second': '315.8', 'eval_steps_per_second': '20.58', 'epoch': '4'}
Fold 5: acc=0.9745 f1=0.9782 best_epoch=3.0

Early-stopped RoBERTa-large Mean accuracy: 0.9765 (std 0.0026)
Early-stopped RoBERTa-large Mean f1:       0.9754 (std 0.0066)
Best epoch per fold: [3.0, 4.0, 4.0, 2.0, 3.0]

Compare to fixed-4-epoch result: accuracy=0.9746, f1=0.9736

In [23]:
train_full_idx = df.index[df["split"] == "trainval"].tolist()
test_idx = df.index[df["split"] == "test"].tolist()

train_full_dataset = Subset(roberta_large_dataset, train_full_idx)
test_dataset = Subset(roberta_large_dataset, test_idx)

print(f"Training on: {len(train_full_dataset)} rows (the full CV pool)")
print(f"Evaluating once on: {len(test_dataset)} rows (never touched before now)")

model = RobertaForSequenceClassification.from_pretrained("roberta-large", num_labels=2)

training_args = TrainingArguments(
    output_dir="./roberta_large_final_eval",
    num_train_epochs=4,              # matches the locked-in configuration, no tuning
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    seed=42,
    eval_strategy="no",              # no mid-training evaluation - we're not selecting anything here
    save_strategy="no",
    logging_steps=50,
    report_to="none",
    disable_tqdm=True,
    fp16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_full_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

trainer.train()
final_test_metrics = trainer.evaluate()
print()
print("=== FINAL HELD-OUT TEST SET RESULT (report this number) ===")
print(final_test_metrics)

Training on: 2071 rows (the full CV pool)
Evaluating once on: 284 rows (never touched before now)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.8564', 'grad_norm': '91.43', 'learning_rate': '1.812e-05', 'epoch': '0.3861'}
{'loss': '0.4013', 'grad_norm': '104.1', 'learning_rate': '1.619e-05', 'epoch': '0.7722'}
{'loss': '0.2538', 'grad_norm': '22.13', 'learning_rate': '1.427e-05', 'epoch': '1.154'}
{'loss': '0.2403', 'grad_norm': '0.02011', 'learning_rate': '1.235e-05', 'epoch': '1.541'}
{'loss': '0.1474', 'grad_norm': '1.235', 'learning_rate': '1.042e-05', 'epoch': '1.927'}
{'loss': '0.09727', 'grad_norm': '0.05132', 'learning_rate': '8.5e-06', 'epoch': '2.309'}
{'loss': '0.07582', 'grad_norm': '2.856', 'learning_rate': '6.577e-06', 'epoch': '2.695'}
{'loss': '0.1245', 'grad_norm': '0.02096', 'learning_rate': '4.654e-06', 'epoch': '3.077'}
{'loss': '0.05528', 'grad_norm': '0.01203', 'learning_rate': '2.731e-06', 'epoch': '3.463'}
{'loss': '0.03335', 'grad_norm': '0.00748', 'learning_rate': '8.077e-07', 'epoch': '3.849'}
{'train_runtime': '139.9', 'train_samples_per_second': '59.21', 'train_steps_per_second': '3.717', 'train_loss': '0.222', 'epoch': '4'}
{'eval_loss': '0.1951', 'eval_accuracy': '0.9683', 'eval_precision': '0.9647', 'eval_recall': '0.982', 'eval_f1': '0.9733', 'eval_runtime': '0.8655', 'eval_samples_per_second': '328.1', 'eval_steps_per_second': '20.8', 'epoch': '4'}

=== FINAL HELD-OUT TEST SET RESULT (report this number) ===
{'eval_loss': 0.19508863985538483, 'eval_accuracy': 0.9683098591549296, 'eval_precision': 0.9647058823529412, 'eval_recall': 0.9820359281437125, 'eval_f1': 0.973293768545994, 'eval_runtime': 0.8655, 'eval_samples_per_second': 328.134, 'eval_steps_per_second': 20.797, 'epoch': 4.0}

In [24]:
full_data_idx = df.index.tolist()  # every row - train+val+test combined
full_training_dataset = Subset(roberta_large_dataset, full_data_idx)

print(f"Training final deployment model on: {len(full_training_dataset)} rows (100% of data)")

final_model = RobertaForSequenceClassification.from_pretrained("roberta-large", num_labels=2)

final_training_args = TrainingArguments(
    output_dir="./roberta_large_deployment",
    num_train_epochs=4,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=2e-5,
    seed=42,
    eval_strategy="no",     # no evaluation - nothing left to hold out, this is the final artifact
    save_strategy="no",
    logging_steps=50,
    report_to="none",
    disable_tqdm=True,
    fp16=True,
)

final_trainer = Trainer(
    model=final_model,
    args=final_training_args,
    train_dataset=full_training_dataset,
)

final_trainer.train()

# Save model + tokenizer together - the backend team needs both
final_model.save_pretrained("./darkguard_deployment_model")
roberta_large_tok.save_pretrained("./darkguard_deployment_model")

import shutil
shutil.make_archive("darkguard_roberta_large_final", "zip", "./darkguard_deployment_model")

print()
print("Saved and zipped: darkguard_roberta_large_final.zip")

Training final deployment model on: 2355 rows (100% of data)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-large
Key                        | Status     |
---------------------------+------------+-
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.8369', 'grad_norm': '9.382', 'learning_rate': '1.834e-05', 'epoch': '0.339'}
{'loss': '0.2615', 'grad_norm': '4.947', 'learning_rate': '1.666e-05', 'epoch': '0.678'}
{'loss': '0.3421', 'grad_norm': '0.06651', 'learning_rate': '1.497e-05', 'epoch': '1.014'}
{'loss': '0.2527', 'grad_norm': '0.3527', 'learning_rate': '1.328e-05', 'epoch': '1.353'}
{'loss': '0.1327', 'grad_norm': '33.64', 'learning_rate': '1.159e-05', 'epoch': '1.692'}
{'loss': '0.2448', 'grad_norm': '0.01478', 'learning_rate': '9.899e-06', 'epoch': '2.027'}
{'loss': '0.1034', 'grad_norm': '0.05786', 'learning_rate': '8.209e-06', 'epoch': '2.366'}
{'loss': '0.06376', 'grad_norm': '0.04142', 'learning_rate': '6.52e-06', 'epoch': '2.705'}
{'loss': '0.0654', 'grad_norm': '0.02332', 'learning_rate': '4.831e-06', 'epoch': '3.041'}
{'loss': '0.003424', 'grad_norm': '0.02746', 'learning_rate': '3.142e-06', 'epoch': '3.38'}
{'loss': '0.03218', 'grad_norm': '0.6671', 'learning_rate': '1.453e-06', 'epoch': '3.719'}
{'train_runtime': '158.5', 'train_samples_per_second': '59.43', 'train_steps_per_second': '3.735', 'train_loss': '0.2001', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved and zipped: darkguard_roberta_large_final.zip